repos:
-   repo: https://github.com/psf/black
    rev: 23.11.0 
    hooks:
    -   id: black
        language_version: python3.9.13

# -   repo: https://github.com/pycqa/flake8
#     rev: 6.1.0
#     hooks:
#     -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.7.1
#     hooks:
#     -   id: mypy

# -   repo: local
#     hooks:
#     -   id: safety
#         name: safety
#         entry: safety check
#         language: system
#         types: [python]

# -   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
#     rev: v1.0.6
#     hooks:
#     -   id: python-bandit-vulnerability-check
#         args: [--level, LOW, --confidence, LOW]

