# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'window.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFormLayout, QFrame,
    QGridLayout, QHBoxLayout, QLabel, QLayout,
    QLineEdit, QMainWindow, QPushButton, QScrollArea,
    QSizePolicy, QSlider, QSpacerItem, QSpinBox,
    QStatusBar, QToolBox, QToolButton, QVBoxLayout,
    QWidget)
from crystalaspects.gui.utils import qticons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1400, 865)
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/program_icon/icon.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionOpen_Simulations = QAction(MainWindow)
        self.actionOpen_Simulations.setObjectName(u"actionOpen_Simulations")
        self.actionOpen_XYZs = QAction(MainWindow)
        self.actionOpen_XYZs.setObjectName(u"actionOpen_XYZs")
        self.actionOpen_Outputs = QAction(MainWindow)
        self.actionOpen_Outputs.setObjectName(u"actionOpen_Outputs")
        self.actionAmber = QAction(MainWindow)
        self.actionAmber.setObjectName(u"actionAmber")
        self.actionBlue = QAction(MainWindow)
        self.actionBlue.setObjectName(u"actionBlue")
        self.actionCyan = QAction(MainWindow)
        self.actionCyan.setObjectName(u"actionCyan")
        self.actionCyan_500 = QAction(MainWindow)
        self.actionCyan_500.setObjectName(u"actionCyan_500")
        self.actionLight_green = QAction(MainWindow)
        self.actionLight_green.setObjectName(u"actionLight_green")
        self.actionPink = QAction(MainWindow)
        self.actionPink.setObjectName(u"actionPink")
        self.actionPurple = QAction(MainWindow)
        self.actionPurple.setObjectName(u"actionPurple")
        self.actionRed_2 = QAction(MainWindow)
        self.actionRed_2.setObjectName(u"actionRed_2")
        self.actionTeal = QAction(MainWindow)
        self.actionTeal.setObjectName(u"actionTeal")
        self.actionYellow = QAction(MainWindow)
        self.actionYellow.setObjectName(u"actionYellow")
        self.actionAmber_2 = QAction(MainWindow)
        self.actionAmber_2.setObjectName(u"actionAmber_2")
        self.actionBlue_2 = QAction(MainWindow)
        self.actionBlue_2.setObjectName(u"actionBlue_2")
        self.actionCyan_2 = QAction(MainWindow)
        self.actionCyan_2.setObjectName(u"actionCyan_2")
        self.actionLight_green_2 = QAction(MainWindow)
        self.actionLight_green_2.setObjectName(u"actionLight_green_2")
        self.actionPink_2 = QAction(MainWindow)
        self.actionPink_2.setObjectName(u"actionPink_2")
        self.actionPurple_2 = QAction(MainWindow)
        self.actionPurple_2.setObjectName(u"actionPurple_2")
        self.actionRed = QAction(MainWindow)
        self.actionRed.setObjectName(u"actionRed")
        self.actionTeal_2 = QAction(MainWindow)
        self.actionTeal_2.setObjectName(u"actionTeal_2")
        self.actionCyan_501 = QAction(MainWindow)
        self.actionCyan_501.setObjectName(u"actionCyan_501")
        self.actionLight_green_3 = QAction(MainWindow)
        self.actionLight_green_3.setObjectName(u"actionLight_green_3")
        self.actionPink_3 = QAction(MainWindow)
        self.actionPink_3.setObjectName(u"actionPink_3")
        self.actionPurple_3 = QAction(MainWindow)
        self.actionPurple_3.setObjectName(u"actionPurple_3")
        self.actionRed_3 = QAction(MainWindow)
        self.actionRed_3.setObjectName(u"actionRed_3")
        self.actionTeal_3 = QAction(MainWindow)
        self.actionTeal_3.setObjectName(u"actionTeal_3")
        self.actionYellow_2 = QAction(MainWindow)
        self.actionYellow_2.setObjectName(u"actionYellow_2")
        self.action_5 = QAction(MainWindow)
        self.action_5.setObjectName(u"action_5")
        self.action_5.setCheckable(False)
        self.action_4 = QAction(MainWindow)
        self.action_4.setObjectName(u"action_4")
        self.action_6 = QAction(MainWindow)
        self.action_6.setObjectName(u"action_6")
        self.action_7 = QAction(MainWindow)
        self.action_7.setObjectName(u"action_7")
        self.action_1 = QAction(MainWindow)
        self.action_1.setObjectName(u"action_1")
        self.action0 = QAction(MainWindow)
        self.action0.setObjectName(u"action0")
        self.action1 = QAction(MainWindow)
        self.action1.setObjectName(u"action1")
        self.action2 = QAction(MainWindow)
        self.action2.setObjectName(u"action2")
        self.action3 = QAction(MainWindow)
        self.action3.setObjectName(u"action3")
        self.action4 = QAction(MainWindow)
        self.action4.setObjectName(u"action4")
        self.action5 = QAction(MainWindow)
        self.action5.setObjectName(u"action5")
        self.actionDensity_2 = QAction(MainWindow)
        self.actionDensity_2.setObjectName(u"actionDensity_2")
        self.actionStyle = QAction(MainWindow)
        self.actionStyle.setObjectName(u"actionStyle")
        self.action_8 = QAction(MainWindow)
        self.action_8.setObjectName(u"action_8")
        self.action_9 = QAction(MainWindow)
        self.action_9.setObjectName(u"action_9")
        self.action_10 = QAction(MainWindow)
        self.action_10.setObjectName(u"action_10")
        self.action_11 = QAction(MainWindow)
        self.action_11.setObjectName(u"action_11")
        self.action0_2 = QAction(MainWindow)
        self.action0_2.setObjectName(u"action0_2")
        self.action1_2 = QAction(MainWindow)
        self.action1_2.setObjectName(u"action1_2")
        self.action2_2 = QAction(MainWindow)
        self.action2_2.setObjectName(u"action2_2")
        self.action3_2 = QAction(MainWindow)
        self.action3_2.setObjectName(u"action3_2")
        self.action4_2 = QAction(MainWindow)
        self.action4_2.setObjectName(u"action4_2")
        self.action_12 = QAction(MainWindow)
        self.action_12.setObjectName(u"action_12")
        self.action_13 = QAction(MainWindow)
        self.action_13.setObjectName(u"action_13")
        self.action_14 = QAction(MainWindow)
        self.action_14.setObjectName(u"action_14")
        self.action0_3 = QAction(MainWindow)
        self.action0_3.setObjectName(u"action0_3")
        self.action1_3 = QAction(MainWindow)
        self.action1_3.setObjectName(u"action1_3")
        self.action2_3 = QAction(MainWindow)
        self.action2_3.setObjectName(u"action2_3")
        self.action3_3 = QAction(MainWindow)
        self.action3_3.setObjectName(u"action3_3")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.import_pushButton = QPushButton(self.centralwidget)
        self.import_pushButton.setObjectName(u"import_pushButton")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_pushButton.sizePolicy().hasHeightForWidth())
        self.import_pushButton.setSizePolicy(sizePolicy)
        self.import_pushButton.setMinimumSize(QSize(150, 45))
        self.import_pushButton.setBaseSize(QSize(0, 0))
        icon1 = QIcon()
        icon1.addFile(u":/material_icons/material_icons/png/folder-arrow-down-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.import_pushButton.setIcon(icon1)
        self.import_pushButton.setIconSize(QSize(25, 25))

        self.gridLayout.addWidget(self.import_pushButton, 0, 0, 1, 1)

        self.view_results_pushButton = QPushButton(self.centralwidget)
        self.view_results_pushButton.setObjectName(u"view_results_pushButton")
        self.view_results_pushButton.setEnabled(False)
        sizePolicy.setHeightForWidth(self.view_results_pushButton.sizePolicy().hasHeightForWidth())
        self.view_results_pushButton.setSizePolicy(sizePolicy)
        self.view_results_pushButton.setMinimumSize(QSize(150, 45))
        self.view_results_pushButton.setBaseSize(QSize(0, 0))
        icon2 = QIcon()
        icon2.addFile(u":/material_icons/material_icons/png/folder-arrow-right-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.view_results_pushButton.setIcon(icon2)
        self.view_results_pushButton.setIconSize(QSize(25, 25))

        self.gridLayout.addWidget(self.view_results_pushButton, 0, 8, 1, 1)

        self.scrollArea_options = QScrollArea(self.centralwidget)
        self.scrollArea_options.setObjectName(u"scrollArea_options")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(5)
        sizePolicy1.setVerticalStretch(4)
        sizePolicy1.setHeightForWidth(self.scrollArea_options.sizePolicy().hasHeightForWidth())
        self.scrollArea_options.setSizePolicy(sizePolicy1)
        self.scrollArea_options.setWidgetResizable(True)
        self.scrollAreaWidgetContents_5 = QWidget()
        self.scrollAreaWidgetContents_5.setObjectName(u"scrollAreaWidgetContents_5")
        self.scrollAreaWidgetContents_5.setGeometry(QRect(0, 0, 393, 774))
        self.verticalLayout_2 = QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.location_label = QLabel(self.scrollAreaWidgetContents_5)
        self.location_label.setObjectName(u"location_label")

        self.verticalLayout_2.addWidget(self.location_label)

        self.batch_lineEdit = QLineEdit(self.scrollAreaWidgetContents_5)
        self.batch_lineEdit.setObjectName(u"batch_lineEdit")
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.batch_lineEdit.sizePolicy().hasHeightForWidth())
        self.batch_lineEdit.setSizePolicy(sizePolicy2)
        self.batch_lineEdit.setMinimumSize(QSize(0, 30))
        self.batch_lineEdit.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.verticalLayout_2.addWidget(self.batch_lineEdit)

        self.calculate_label = QLabel(self.scrollAreaWidgetContents_5)
        self.calculate_label.setObjectName(u"calculate_label")

        self.verticalLayout_2.addWidget(self.calculate_label)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.aspect_ratio_pushButton = QPushButton(self.scrollAreaWidgetContents_5)
        self.aspect_ratio_pushButton.setObjectName(u"aspect_ratio_pushButton")
        self.aspect_ratio_pushButton.setEnabled(False)
        sizePolicy3 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.aspect_ratio_pushButton.sizePolicy().hasHeightForWidth())
        self.aspect_ratio_pushButton.setSizePolicy(sizePolicy3)
        self.aspect_ratio_pushButton.setMinimumSize(QSize(0, 45))

        self.horizontalLayout_2.addWidget(self.aspect_ratio_pushButton)

        self.growth_rate_pushButton = QPushButton(self.scrollAreaWidgetContents_5)
        self.growth_rate_pushButton.setObjectName(u"growth_rate_pushButton")
        self.growth_rate_pushButton.setEnabled(False)
        sizePolicy3.setHeightForWidth(self.growth_rate_pushButton.sizePolicy().hasHeightForWidth())
        self.growth_rate_pushButton.setSizePolicy(sizePolicy3)
        self.growth_rate_pushButton.setMinimumSize(QSize(0, 45))
        self.growth_rate_pushButton.setIconSize(QSize(16, 16))

        self.horizontalLayout_2.addWidget(self.growth_rate_pushButton)


        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.plot_label = QLabel(self.scrollAreaWidgetContents_5)
        self.plot_label.setObjectName(u"plot_label")

        self.verticalLayout_2.addWidget(self.plot_label)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.plot_lineEdit = QLineEdit(self.scrollAreaWidgetContents_5)
        self.plot_lineEdit.setObjectName(u"plot_lineEdit")
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(5)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.plot_lineEdit.sizePolicy().hasHeightForWidth())
        self.plot_lineEdit.setSizePolicy(sizePolicy4)
        self.plot_lineEdit.setMinimumSize(QSize(0, 30))
        self.plot_lineEdit.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.horizontalLayout_4.addWidget(self.plot_lineEdit)

        self.plot_browse_toolButton = QToolButton(self.scrollAreaWidgetContents_5)
        self.plot_browse_toolButton.setObjectName(u"plot_browse_toolButton")
        self.plot_browse_toolButton.setMinimumSize(QSize(38, 38))
        icon3 = QIcon()
        icon3.addFile(u":/material_icons/material_icons/png/file-table-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.plot_browse_toolButton.setIcon(icon3)
        self.plot_browse_toolButton.setIconSize(QSize(25, 25))

        self.horizontalLayout_4.addWidget(self.plot_browse_toolButton)


        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.plot_pushButton = QPushButton(self.scrollAreaWidgetContents_5)
        self.plot_pushButton.setObjectName(u"plot_pushButton")
        self.plot_pushButton.setEnabled(False)
        self.plot_pushButton.setMinimumSize(QSize(0, 45))
        icon4 = QIcon()
        icon4.addFile(u":/material_icons/material_icons/png/chart-scatter-plot-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.plot_pushButton.setIcon(icon4)
        self.plot_pushButton.setIconSize(QSize(25, 25))

        self.verticalLayout_2.addWidget(self.plot_pushButton)

        self.xyz_id_frame = QFrame(self.scrollAreaWidgetContents_5)
        self.xyz_id_frame.setObjectName(u"xyz_id_frame")
        self.xyz_id_frame.setFrameShape(QFrame.StyledPanel)
        self.xyz_id_frame.setFrameShadow(QFrame.Raised)
        self.gridLayout_5 = QGridLayout(self.xyz_id_frame)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.xyz_spinBox = QSpinBox(self.xyz_id_frame)
        self.xyz_spinBox.setObjectName(u"xyz_spinBox")
        self.xyz_spinBox.setMinimumSize(QSize(0, 0))
        self.xyz_spinBox.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.gridLayout_5.addWidget(self.xyz_spinBox, 0, 1, 1, 1)

        self.saveframe_toolButton = QToolButton(self.xyz_id_frame)
        self.saveframe_toolButton.setObjectName(u"saveframe_toolButton")
        icon5 = QIcon()
        icon5.addFile(u":/material_icons/material_icons/png/content-save-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.saveframe_toolButton.setIcon(icon5)
        self.saveframe_toolButton.setIconSize(QSize(25, 25))

        self.gridLayout_5.addWidget(self.saveframe_toolButton, 0, 2, 1, 1)

        self.fname_comboBox = QComboBox(self.xyz_id_frame)
        self.fname_comboBox.setObjectName(u"fname_comboBox")
        sizePolicy5 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy5.setHorizontalStretch(1)
        sizePolicy5.setVerticalStretch(1)
        sizePolicy5.setHeightForWidth(self.fname_comboBox.sizePolicy().hasHeightForWidth())
        self.fname_comboBox.setSizePolicy(sizePolicy5)
        self.fname_comboBox.setMinimumSize(QSize(0, 0))
        font1 = QFont()
        font1.setKerning(True)
        self.fname_comboBox.setFont(font1)
        self.fname_comboBox.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.gridLayout_5.addWidget(self.fname_comboBox, 4, 0, 1, 3)

        self.xyz_id_label = QLabel(self.xyz_id_frame)
        self.xyz_id_label.setObjectName(u"xyz_id_label")

        self.gridLayout_5.addWidget(self.xyz_id_label, 0, 0, 1, 1)


        self.verticalLayout_2.addWidget(self.xyz_id_frame)

        self.main_toolBox = QToolBox(self.scrollAreaWidgetContents_5)
        self.main_toolBox.setObjectName(u"main_toolBox")
        sizePolicy6 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(3)
        sizePolicy6.setHeightForWidth(self.main_toolBox.sizePolicy().hasHeightForWidth())
        self.main_toolBox.setSizePolicy(sizePolicy6)
        self.main_toolBox.setMinimumSize(QSize(0, 375))
        font2 = QFont()
        font2.setPointSize(12)
        self.main_toolBox.setFont(font2)
        self.variables_tab = QWidget()
        self.variables_tab.setObjectName(u"variables_tab")
        self.variables_tab.setGeometry(QRect(0, 0, 369, 311))
        self.gridLayout_7 = QGridLayout(self.variables_tab)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.EVariable_title_label_2 = QLabel(self.variables_tab)
        self.EVariable_title_label_2.setObjectName(u"EVariable_title_label_2")
        font3 = QFont()
        font3.setFamilies([u"Arial"])
        font3.setPointSize(10)
        font3.setBold(True)
        font3.setItalic(False)
        self.EVariable_title_label_2.setFont(font3)

        self.gridLayout_7.addWidget(self.EVariable_title_label_2, 1, 0, 1, 1)

        self.select_summary_slider_button = QPushButton(self.variables_tab)
        self.select_summary_slider_button.setObjectName(u"select_summary_slider_button")
        self.select_summary_slider_button.setEnabled(False)
        sizePolicy7 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(1)
        sizePolicy7.setHeightForWidth(self.select_summary_slider_button.sizePolicy().hasHeightForWidth())
        self.select_summary_slider_button.setSizePolicy(sizePolicy7)
        self.select_summary_slider_button.setMinimumSize(QSize(200, 0))
        self.select_summary_slider_button.setFont(font3)

        self.gridLayout_7.addWidget(self.select_summary_slider_button, 0, 0, 1, 1, Qt.AlignLeft)

        self.E_variables_layout = QGridLayout()
        self.E_variables_layout.setObjectName(u"E_variables_layout")
        self.E_variables_layout.setSizeConstraint(QLayout.SetNoConstraint)

        self.gridLayout_7.addLayout(self.E_variables_layout, 2, 0, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_7.addItem(self.verticalSpacer, 3, 0, 1, 1)

        self.main_toolBox.addItem(self.variables_tab, u"Variables")
        self.crystal_info_tab = QWidget()
        self.crystal_info_tab.setObjectName(u"crystal_info_tab")
        self.crystal_info_tab.setGeometry(QRect(0, 0, 369, 311))
        self.gridLayout_2 = QGridLayout(self.crystal_info_tab)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.formLayout = QFormLayout()
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setFieldGrowthPolicy(QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.formLayout.setFormAlignment(Qt.AlignCenter)
        self.formLayout.setHorizontalSpacing(-1)
        self.formLayout.setVerticalSpacing(7)
        self.formLayout.setContentsMargins(10, -1, 10, -1)
        self.lineEdit_uc_lengths = QLineEdit(self.crystal_info_tab)
        self.lineEdit_uc_lengths.setObjectName(u"lineEdit_uc_lengths")
        sizePolicy8 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy8.setHorizontalStretch(1)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.lineEdit_uc_lengths.sizePolicy().hasHeightForWidth())
        self.lineEdit_uc_lengths.setSizePolicy(sizePolicy8)
        self.lineEdit_uc_lengths.setMinimumSize(QSize(0, 0))
        self.lineEdit_uc_lengths.setFont(font)
        self.lineEdit_uc_lengths.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lineEdit_uc_lengths.setReadOnly(True)

        self.formLayout.setWidget(7, QFormLayout.FieldRole, self.lineEdit_uc_lengths)

        self.label_9 = QLabel(self.crystal_info_tab)
        self.label_9.setObjectName(u"label_9")

        self.formLayout.setWidget(8, QFormLayout.LabelRole, self.label_9)

        self.lineEdit_uc_angles = QLineEdit(self.crystal_info_tab)
        self.lineEdit_uc_angles.setObjectName(u"lineEdit_uc_angles")
        sizePolicy8.setHeightForWidth(self.lineEdit_uc_angles.sizePolicy().hasHeightForWidth())
        self.lineEdit_uc_angles.setSizePolicy(sizePolicy8)
        self.lineEdit_uc_angles.setMinimumSize(QSize(0, 0))
        self.lineEdit_uc_angles.setFont(font)
        self.lineEdit_uc_angles.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lineEdit_uc_angles.setReadOnly(True)

        self.formLayout.setWidget(8, QFormLayout.FieldRole, self.lineEdit_uc_angles)

        self.label_8 = QLabel(self.crystal_info_tab)
        self.label_8.setObjectName(u"label_8")

        self.formLayout.setWidget(7, QFormLayout.LabelRole, self.label_8)

        self.lineEdit_spaceg = QLineEdit(self.crystal_info_tab)
        self.lineEdit_spaceg.setObjectName(u"lineEdit_spaceg")
        sizePolicy8.setHeightForWidth(self.lineEdit_spaceg.sizePolicy().hasHeightForWidth())
        self.lineEdit_spaceg.setSizePolicy(sizePolicy8)
        self.lineEdit_spaceg.setMinimumSize(QSize(0, 0))
        self.lineEdit_spaceg.setFont(font2)
        self.lineEdit_spaceg.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lineEdit_spaceg.setReadOnly(True)

        self.formLayout.setWidget(6, QFormLayout.FieldRole, self.lineEdit_spaceg)

        self.label_7 = QLabel(self.crystal_info_tab)
        self.label_7.setObjectName(u"label_7")

        self.formLayout.setWidget(6, QFormLayout.LabelRole, self.label_7)

        self.lineEdit_vol = QLineEdit(self.crystal_info_tab)
        self.lineEdit_vol.setObjectName(u"lineEdit_vol")
        sizePolicy8.setHeightForWidth(self.lineEdit_vol.sizePolicy().hasHeightForWidth())
        self.lineEdit_vol.setSizePolicy(sizePolicy8)
        self.lineEdit_vol.setMinimumSize(QSize(0, 0))
        self.lineEdit_vol.setFont(font2)
        self.lineEdit_vol.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lineEdit_vol.setReadOnly(True)

        self.formLayout.setWidget(5, QFormLayout.FieldRole, self.lineEdit_vol)

        self.label_6 = QLabel(self.crystal_info_tab)
        self.label_6.setObjectName(u"label_6")

        self.formLayout.setWidget(5, QFormLayout.LabelRole, self.label_6)

        self.lineEdit_sa = QLineEdit(self.crystal_info_tab)
        self.lineEdit_sa.setObjectName(u"lineEdit_sa")
        sizePolicy8.setHeightForWidth(self.lineEdit_sa.sizePolicy().hasHeightForWidth())
        self.lineEdit_sa.setSizePolicy(sizePolicy8)
        self.lineEdit_sa.setMinimumSize(QSize(0, 0))
        self.lineEdit_sa.setFont(font2)
        self.lineEdit_sa.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lineEdit_sa.setReadOnly(True)

        self.formLayout.setWidget(4, QFormLayout.FieldRole, self.lineEdit_sa)

        self.label_5 = QLabel(self.crystal_info_tab)
        self.label_5.setObjectName(u"label_5")

        self.formLayout.setWidget(4, QFormLayout.LabelRole, self.label_5)

        self.lineEdit_savol = QLineEdit(self.crystal_info_tab)
        self.lineEdit_savol.setObjectName(u"lineEdit_savol")
        sizePolicy8.setHeightForWidth(self.lineEdit_savol.sizePolicy().hasHeightForWidth())
        self.lineEdit_savol.setSizePolicy(sizePolicy8)
        self.lineEdit_savol.setMinimumSize(QSize(0, 0))
        self.lineEdit_savol.setFont(font2)
        self.lineEdit_savol.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lineEdit_savol.setReadOnly(True)

        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.lineEdit_savol)

        self.label_4 = QLabel(self.crystal_info_tab)
        self.label_4.setObjectName(u"label_4")

        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.label_4)

        self.lineEdit_shape = QLineEdit(self.crystal_info_tab)
        self.lineEdit_shape.setObjectName(u"lineEdit_shape")
        sizePolicy8.setHeightForWidth(self.lineEdit_shape.sizePolicy().hasHeightForWidth())
        self.lineEdit_shape.setSizePolicy(sizePolicy8)
        self.lineEdit_shape.setMinimumSize(QSize(0, 0))
        self.lineEdit_shape.setFont(font2)
        self.lineEdit_shape.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lineEdit_shape.setReadOnly(True)

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.lineEdit_shape)

        self.label_3 = QLabel(self.crystal_info_tab)
        self.label_3.setObjectName(u"label_3")

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.label_3)

        self.lineEdit_ml = QLineEdit(self.crystal_info_tab)
        self.lineEdit_ml.setObjectName(u"lineEdit_ml")
        sizePolicy8.setHeightForWidth(self.lineEdit_ml.sizePolicy().hasHeightForWidth())
        self.lineEdit_ml.setSizePolicy(sizePolicy8)
        self.lineEdit_ml.setMinimumSize(QSize(0, 0))
        self.lineEdit_ml.setFont(font2)
        self.lineEdit_ml.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lineEdit_ml.setReadOnly(True)

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.lineEdit_ml)

        self.label_2 = QLabel(self.crystal_info_tab)
        self.label_2.setObjectName(u"label_2")

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.label_2)

        self.lineEdit_sm = QLineEdit(self.crystal_info_tab)
        self.lineEdit_sm.setObjectName(u"lineEdit_sm")
        sizePolicy8.setHeightForWidth(self.lineEdit_sm.sizePolicy().hasHeightForWidth())
        self.lineEdit_sm.setSizePolicy(sizePolicy8)
        self.lineEdit_sm.setMinimumSize(QSize(0, 0))
        self.lineEdit_sm.setFont(font2)
        self.lineEdit_sm.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lineEdit_sm.setReadOnly(True)

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.lineEdit_sm)

        self.label = QLabel(self.crystal_info_tab)
        self.label.setObjectName(u"label")

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.label)


        self.gridLayout_2.addLayout(self.formLayout, 1, 0, 1, 1)

        self.main_toolBox.addItem(self.crystal_info_tab, u"Crystal Information")

        self.verticalLayout_2.addWidget(self.main_toolBox)

        self.scrollArea_options.setWidget(self.scrollAreaWidgetContents_5)

        self.gridLayout.addWidget(self.scrollArea_options, 3, 0, 2, 3)

        self.settings_toolButton = QToolButton(self.centralwidget)
        self.settings_toolButton.setObjectName(u"settings_toolButton")
        self.settings_toolButton.setEnabled(True)
        self.settings_toolButton.setMinimumSize(QSize(0, 0))
        icon6 = QIcon()
        icon6.addFile(u":/material_icons/material_icons/png/cog-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.settings_toolButton.setIcon(icon6)
        self.settings_toolButton.setIconSize(QSize(25, 25))
        self.settings_toolButton.setAutoRaise(False)

        self.gridLayout.addWidget(self.settings_toolButton, 0, 9, 1, 1)

        self.vis_scrollArea = QScrollArea(self.centralwidget)
        self.vis_scrollArea.setObjectName(u"vis_scrollArea")
        sizePolicy9 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy9.setHorizontalStretch(30)
        sizePolicy9.setVerticalStretch(0)
        sizePolicy9.setHeightForWidth(self.vis_scrollArea.sizePolicy().hasHeightForWidth())
        self.vis_scrollArea.setSizePolicy(sizePolicy9)
        self.vis_scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 969, 774))
        self.gridLayout_3 = QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.main_frame = QFrame(self.scrollAreaWidgetContents_4)
        self.main_frame.setObjectName(u"main_frame")
        sizePolicy10 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy10.setHorizontalStretch(0)
        sizePolicy10.setVerticalStretch(5)
        sizePolicy10.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy10)
        self.gl_vLayout = QGridLayout(self.main_frame)
        self.gl_vLayout.setObjectName(u"gl_vLayout")

        self.gridLayout_3.addWidget(self.main_frame, 0, 0, 1, 2)

        self.movie_controls_frame = QFrame(self.scrollAreaWidgetContents_4)
        self.movie_controls_frame.setObjectName(u"movie_controls_frame")
        self.movie_controls_frame.setStyleSheet(u"background-color: rgb(58, 64, 85);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 12px;")
        self.movie_controls_frame.setFrameShape(QFrame.StyledPanel)
        self.movie_controls_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.movie_controls_frame)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.frame_slider = QSlider(self.movie_controls_frame)
        self.frame_slider.setObjectName(u"frame_slider")
        sizePolicy2.setHeightForWidth(self.frame_slider.sizePolicy().hasHeightForWidth())
        self.frame_slider.setSizePolicy(sizePolicy2)
        self.frame_slider.setOrientation(Qt.Horizontal)

        self.horizontalLayout_5.addWidget(self.frame_slider)

        self.frame_spinBox = QSpinBox(self.movie_controls_frame)
        self.frame_spinBox.setObjectName(u"frame_spinBox")

        self.horizontalLayout_5.addWidget(self.frame_spinBox)

        self.start_simvis_button = QToolButton(self.movie_controls_frame)
        self.start_simvis_button.setObjectName(u"start_simvis_button")
        self.start_simvis_button.setMinimumSize(QSize(0, 0))
        icon7 = QIcon()
        icon7.addFile(u":/material_icons/material_icons/png/skip-backward-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.start_simvis_button.setIcon(icon7)

        self.horizontalLayout_5.addWidget(self.start_simvis_button)

        self.previous_button = QToolButton(self.movie_controls_frame)
        self.previous_button.setObjectName(u"previous_button")
        self.previous_button.setMinimumSize(QSize(0, 0))
        icon8 = QIcon()
        icon8.addFile(u":/material_icons/material_icons/png/skip-previous-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.previous_button.setIcon(icon8)

        self.horizontalLayout_5.addWidget(self.previous_button)

        self.play_button = QToolButton(self.movie_controls_frame)
        self.play_button.setObjectName(u"play_button")
        self.play_button.setMinimumSize(QSize(0, 0))
        icon9 = QIcon()
        icon9.addFile(u":/material_icons/material_icons/png/play-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.play_button.setIcon(icon9)

        self.horizontalLayout_5.addWidget(self.play_button)

        self.pause_button = QToolButton(self.movie_controls_frame)
        self.pause_button.setObjectName(u"pause_button")
        self.pause_button.setMinimumSize(QSize(0, 0))
        icon10 = QIcon()
        icon10.addFile(u":/material_icons/material_icons/png/pause-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pause_button.setIcon(icon10)

        self.horizontalLayout_5.addWidget(self.pause_button)

        self.next_button = QToolButton(self.movie_controls_frame)
        self.next_button.setObjectName(u"next_button")
        self.next_button.setMinimumSize(QSize(0, 0))
        icon11 = QIcon()
        icon11.addFile(u":/material_icons/material_icons/png/skip-next-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.next_button.setIcon(icon11)

        self.horizontalLayout_5.addWidget(self.next_button)

        self.end_simvis_button = QToolButton(self.movie_controls_frame)
        self.end_simvis_button.setObjectName(u"end_simvis_button")
        self.end_simvis_button.setMinimumSize(QSize(0, 0))
        icon12 = QIcon()
        icon12.addFile(u":/material_icons/material_icons/png/skip-forward-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.end_simvis_button.setIcon(icon12)

        self.horizontalLayout_5.addWidget(self.end_simvis_button)


        self.gridLayout_3.addWidget(self.movie_controls_frame, 1, 0, 1, 2)

        self.vis_scrollArea.setWidget(self.scrollAreaWidgetContents_4)

        self.gridLayout.addWidget(self.vis_scrollArea, 3, 7, 2, 3)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        font4 = QFont()
        font4.setFamilies([u"Arial"])
        font4.setPointSize(8)
        font4.setItalic(True)
        self.statusbar.setFont(font4)
        self.statusbar.setCursor(QCursor(Qt.ArrowCursor))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.main_toolBox.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"CrystalAspects", None))
        self.actionOpen_Simulations.setText(QCoreApplication.translate("MainWindow", u"Open Simulations", None))
        self.actionOpen_XYZs.setText(QCoreApplication.translate("MainWindow", u"Open XYZs", None))
        self.actionOpen_Outputs.setText(QCoreApplication.translate("MainWindow", u"Open Outputs", None))
        self.actionAmber.setText(QCoreApplication.translate("MainWindow", u"Amber", None))
        self.actionBlue.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
        self.actionCyan.setText(QCoreApplication.translate("MainWindow", u"Cyan", None))
        self.actionCyan_500.setText(QCoreApplication.translate("MainWindow", u"Cyan-500", None))
        self.actionLight_green.setText(QCoreApplication.translate("MainWindow", u"Light-green", None))
        self.actionPink.setText(QCoreApplication.translate("MainWindow", u"Pink", None))
        self.actionPurple.setText(QCoreApplication.translate("MainWindow", u"Purple", None))
        self.actionRed_2.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.actionTeal.setText(QCoreApplication.translate("MainWindow", u"Teal", None))
        self.actionYellow.setText(QCoreApplication.translate("MainWindow", u"Yellow", None))
        self.actionAmber_2.setText(QCoreApplication.translate("MainWindow", u"Amber", None))
        self.actionBlue_2.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
        self.actionCyan_2.setText(QCoreApplication.translate("MainWindow", u"Cyan", None))
        self.actionLight_green_2.setText(QCoreApplication.translate("MainWindow", u"Light-green", None))
        self.actionPink_2.setText(QCoreApplication.translate("MainWindow", u"Pink", None))
        self.actionPurple_2.setText(QCoreApplication.translate("MainWindow", u"Purple", None))
        self.actionRed.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.actionTeal_2.setText(QCoreApplication.translate("MainWindow", u"Teal", None))
        self.actionCyan_501.setText(QCoreApplication.translate("MainWindow", u"Cyan-500", None))
        self.actionLight_green_3.setText(QCoreApplication.translate("MainWindow", u"Light-green", None))
        self.actionPink_3.setText(QCoreApplication.translate("MainWindow", u"Pink", None))
        self.actionPurple_3.setText(QCoreApplication.translate("MainWindow", u"Purple", None))
        self.actionRed_3.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.actionTeal_3.setText(QCoreApplication.translate("MainWindow", u"Teal", None))
        self.actionYellow_2.setText(QCoreApplication.translate("MainWindow", u"Yellow", None))
        self.action_5.setText(QCoreApplication.translate("MainWindow", u"-5", None))
        self.action_4.setText(QCoreApplication.translate("MainWindow", u"-4", None))
        self.action_6.setText(QCoreApplication.translate("MainWindow", u"-3", None))
        self.action_7.setText(QCoreApplication.translate("MainWindow", u"-2", None))
        self.action_1.setText(QCoreApplication.translate("MainWindow", u"-1", None))
        self.action0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.action1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.action2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.action3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.action4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.action5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.actionDensity_2.setText(QCoreApplication.translate("MainWindow", u"Density", None))
        self.actionStyle.setText(QCoreApplication.translate("MainWindow", u"Style", None))
        self.action_8.setText(QCoreApplication.translate("MainWindow", u"-4", None))
        self.action_9.setText(QCoreApplication.translate("MainWindow", u"-3", None))
        self.action_10.setText(QCoreApplication.translate("MainWindow", u"-2", None))
        self.action_11.setText(QCoreApplication.translate("MainWindow", u"-1", None))
        self.action0_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.action1_2.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.action2_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.action3_2.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.action4_2.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.action_12.setText(QCoreApplication.translate("MainWindow", u"-3", None))
        self.action_13.setText(QCoreApplication.translate("MainWindow", u"-2", None))
        self.action_14.setText(QCoreApplication.translate("MainWindow", u"-1", None))
        self.action0_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.action1_3.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.action2_3.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.action3_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.import_pushButton.setText(QCoreApplication.translate("MainWindow", u"   Import", None))
        self.view_results_pushButton.setText(QCoreApplication.translate("MainWindow", u"   View Results Directory", None))
        self.location_label.setText(QCoreApplication.translate("MainWindow", u"Location:", None))
        self.calculate_label.setText(QCoreApplication.translate("MainWindow", u"Calculate:", None))
        self.aspect_ratio_pushButton.setText(QCoreApplication.translate("MainWindow", u"Aspect Ratios", None))
        self.growth_rate_pushButton.setText(QCoreApplication.translate("MainWindow", u"Growth Rates", None))
        self.plot_label.setText(QCoreApplication.translate("MainWindow", u"Plotting (CSV):", None))
        self.plot_browse_toolButton.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
#if QT_CONFIG(tooltip)
        self.plot_pushButton.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.plot_pushButton.setText(QCoreApplication.translate("MainWindow", u"   Plot", None))
#if QT_CONFIG(statustip)
        self.saveframe_toolButton.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.saveframe_toolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.xyz_id_label.setText(QCoreApplication.translate("MainWindow", u"XYZ ID: ", None))
        self.EVariable_title_label_2.setText(QCoreApplication.translate("MainWindow", u"Variables:", None))
        self.select_summary_slider_button.setText(QCoreApplication.translate("MainWindow", u"Select Summary File", None))
        self.main_toolBox.setItemText(self.main_toolBox.indexOf(self.variables_tab), QCoreApplication.translate("MainWindow", u"Variables", None))
#if QT_CONFIG(tooltip)
        self.label_9.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Unit cell angles (<span style=\" font-weight:600;\">\u03b1 \u03b2 \u03b3</span>)</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_8.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Unit cell lengths(<b>a b c</b>)", None))
#if QT_CONFIG(tooltip)
        self.label_7.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Space Group", None))
#if QT_CONFIG(tooltip)
        self.label_6.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Volume (<span style=\" font-weight:600;\">nm</span><span style=\" font-weight:600; vertical-align:super;\">3</span>)</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_5.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Surface Area (<span style=\" font-weight:600;\">nm</span><span style=\" font-weight:600; vertical-align:super;\">2</span>)</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_4.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Surface Area : Volume", None))
#if QT_CONFIG(tooltip)
        self.label_3.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"General Shape", None))
#if QT_CONFIG(tooltip)
        self.label_2.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Aspect Ratio M:L", None))
        self.lineEdit_sm.setText("")
#if QT_CONFIG(tooltip)
        self.label.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label.setText(QCoreApplication.translate("MainWindow", u"Aspect Ratio S:M", None))
        self.main_toolBox.setItemText(self.main_toolBox.indexOf(self.crystal_info_tab), QCoreApplication.translate("MainWindow", u"Crystal Information", None))
#if QT_CONFIG(statustip)
        self.settings_toolButton.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.settings_toolButton.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.start_simvis_button.setText("")
        self.previous_button.setText(QCoreApplication.translate("MainWindow", u"   Previous", None))
        self.play_button.setText(QCoreApplication.translate("MainWindow", u"   Play", None))
        self.pause_button.setText(QCoreApplication.translate("MainWindow", u"   Pause", None))
        self.next_button.setText(QCoreApplication.translate("MainWindow", u"   Next", None))
        self.end_simvis_button.setText(QCoreApplication.translate("MainWindow", u"   End", None))
    # retranslateUi

