# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'window.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFormLayout, QFrame,
    QGridLayout, QGroupBox, QHBoxLayout, QLabel,
    QLineEdit, QMainWindow, QPushButton, QScrollArea,
    QSizePolicy, QSlider, QSpacerItem, QSpinBox,
    QStatusBar, QTabWidget, QToolButton, QVBoxLayout,
    QWidget)
from crystalaspects.gui.utils import qticons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1400, 876)
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/app_icons/app_icons/CrystalAspects.icns", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionOpen_Simulations = QAction(MainWindow)
        self.actionOpen_Simulations.setObjectName(u"actionOpen_Simulations")
        self.actionOpen_XYZs = QAction(MainWindow)
        self.actionOpen_XYZs.setObjectName(u"actionOpen_XYZs")
        self.actionOpen_Outputs = QAction(MainWindow)
        self.actionOpen_Outputs.setObjectName(u"actionOpen_Outputs")
        self.actionAmber = QAction(MainWindow)
        self.actionAmber.setObjectName(u"actionAmber")
        self.actionBlue = QAction(MainWindow)
        self.actionBlue.setObjectName(u"actionBlue")
        self.actionCyan = QAction(MainWindow)
        self.actionCyan.setObjectName(u"actionCyan")
        self.actionCyan_500 = QAction(MainWindow)
        self.actionCyan_500.setObjectName(u"actionCyan_500")
        self.actionLight_green = QAction(MainWindow)
        self.actionLight_green.setObjectName(u"actionLight_green")
        self.actionPink = QAction(MainWindow)
        self.actionPink.setObjectName(u"actionPink")
        self.actionPurple = QAction(MainWindow)
        self.actionPurple.setObjectName(u"actionPurple")
        self.actionRed_2 = QAction(MainWindow)
        self.actionRed_2.setObjectName(u"actionRed_2")
        self.actionTeal = QAction(MainWindow)
        self.actionTeal.setObjectName(u"actionTeal")
        self.actionYellow = QAction(MainWindow)
        self.actionYellow.setObjectName(u"actionYellow")
        self.actionAmber_2 = QAction(MainWindow)
        self.actionAmber_2.setObjectName(u"actionAmber_2")
        self.actionBlue_2 = QAction(MainWindow)
        self.actionBlue_2.setObjectName(u"actionBlue_2")
        self.actionCyan_2 = QAction(MainWindow)
        self.actionCyan_2.setObjectName(u"actionCyan_2")
        self.actionLight_green_2 = QAction(MainWindow)
        self.actionLight_green_2.setObjectName(u"actionLight_green_2")
        self.actionPink_2 = QAction(MainWindow)
        self.actionPink_2.setObjectName(u"actionPink_2")
        self.actionPurple_2 = QAction(MainWindow)
        self.actionPurple_2.setObjectName(u"actionPurple_2")
        self.actionRed = QAction(MainWindow)
        self.actionRed.setObjectName(u"actionRed")
        self.actionTeal_2 = QAction(MainWindow)
        self.actionTeal_2.setObjectName(u"actionTeal_2")
        self.actionCyan_501 = QAction(MainWindow)
        self.actionCyan_501.setObjectName(u"actionCyan_501")
        self.actionLight_green_3 = QAction(MainWindow)
        self.actionLight_green_3.setObjectName(u"actionLight_green_3")
        self.actionPink_3 = QAction(MainWindow)
        self.actionPink_3.setObjectName(u"actionPink_3")
        self.actionPurple_3 = QAction(MainWindow)
        self.actionPurple_3.setObjectName(u"actionPurple_3")
        self.actionRed_3 = QAction(MainWindow)
        self.actionRed_3.setObjectName(u"actionRed_3")
        self.actionTeal_3 = QAction(MainWindow)
        self.actionTeal_3.setObjectName(u"actionTeal_3")
        self.actionYellow_2 = QAction(MainWindow)
        self.actionYellow_2.setObjectName(u"actionYellow_2")
        self.action_5 = QAction(MainWindow)
        self.action_5.setObjectName(u"action_5")
        self.action_5.setCheckable(False)
        self.action_4 = QAction(MainWindow)
        self.action_4.setObjectName(u"action_4")
        self.action_6 = QAction(MainWindow)
        self.action_6.setObjectName(u"action_6")
        self.action_7 = QAction(MainWindow)
        self.action_7.setObjectName(u"action_7")
        self.action_1 = QAction(MainWindow)
        self.action_1.setObjectName(u"action_1")
        self.action0 = QAction(MainWindow)
        self.action0.setObjectName(u"action0")
        self.action1 = QAction(MainWindow)
        self.action1.setObjectName(u"action1")
        self.action2 = QAction(MainWindow)
        self.action2.setObjectName(u"action2")
        self.action3 = QAction(MainWindow)
        self.action3.setObjectName(u"action3")
        self.action4 = QAction(MainWindow)
        self.action4.setObjectName(u"action4")
        self.action5 = QAction(MainWindow)
        self.action5.setObjectName(u"action5")
        self.actionDensity_2 = QAction(MainWindow)
        self.actionDensity_2.setObjectName(u"actionDensity_2")
        self.actionStyle = QAction(MainWindow)
        self.actionStyle.setObjectName(u"actionStyle")
        self.action_8 = QAction(MainWindow)
        self.action_8.setObjectName(u"action_8")
        self.action_9 = QAction(MainWindow)
        self.action_9.setObjectName(u"action_9")
        self.action_10 = QAction(MainWindow)
        self.action_10.setObjectName(u"action_10")
        self.action_11 = QAction(MainWindow)
        self.action_11.setObjectName(u"action_11")
        self.action0_2 = QAction(MainWindow)
        self.action0_2.setObjectName(u"action0_2")
        self.action1_2 = QAction(MainWindow)
        self.action1_2.setObjectName(u"action1_2")
        self.action2_2 = QAction(MainWindow)
        self.action2_2.setObjectName(u"action2_2")
        self.action3_2 = QAction(MainWindow)
        self.action3_2.setObjectName(u"action3_2")
        self.action4_2 = QAction(MainWindow)
        self.action4_2.setObjectName(u"action4_2")
        self.action_12 = QAction(MainWindow)
        self.action_12.setObjectName(u"action_12")
        self.action_13 = QAction(MainWindow)
        self.action_13.setObjectName(u"action_13")
        self.action_14 = QAction(MainWindow)
        self.action_14.setObjectName(u"action_14")
        self.action0_3 = QAction(MainWindow)
        self.action0_3.setObjectName(u"action0_3")
        self.action1_3 = QAction(MainWindow)
        self.action1_3.setObjectName(u"action1_3")
        self.action2_3 = QAction(MainWindow)
        self.action2_3.setObjectName(u"action2_3")
        self.action3_3 = QAction(MainWindow)
        self.action3_3.setObjectName(u"action3_3")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.vis_scrollArea = QScrollArea(self.centralwidget)
        self.vis_scrollArea.setObjectName(u"vis_scrollArea")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vis_scrollArea.sizePolicy().hasHeightForWidth())
        self.vis_scrollArea.setSizePolicy(sizePolicy)
        self.vis_scrollArea.setFrameShape(QFrame.NoFrame)
        self.vis_scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 1037, 825))
        self.gridLayout_3 = QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.main_frame = QFrame(self.scrollAreaWidgetContents_4)
        self.main_frame.setObjectName(u"main_frame")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(5)
        sizePolicy1.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy1)
        self.gl_vLayout = QGridLayout(self.main_frame)
        self.gl_vLayout.setObjectName(u"gl_vLayout")

        self.gridLayout_3.addWidget(self.main_frame, 0, 0, 1, 2)

        self.movie_controls_frame = QFrame(self.scrollAreaWidgetContents_4)
        self.movie_controls_frame.setObjectName(u"movie_controls_frame")
        self.movie_controls_frame.setStyleSheet(u"")
        self.movie_controls_frame.setFrameShape(QFrame.StyledPanel)
        self.movie_controls_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.movie_controls_frame)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.frame_slider = QSlider(self.movie_controls_frame)
        self.frame_slider.setObjectName(u"frame_slider")
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.frame_slider.sizePolicy().hasHeightForWidth())
        self.frame_slider.setSizePolicy(sizePolicy2)
        self.frame_slider.setOrientation(Qt.Horizontal)
        self.frame_slider.setTickPosition(QSlider.TicksBelow)

        self.horizontalLayout_5.addWidget(self.frame_slider)

        self.frame_spinBox = QSpinBox(self.movie_controls_frame)
        self.frame_spinBox.setObjectName(u"frame_spinBox")

        self.horizontalLayout_5.addWidget(self.frame_spinBox)

        self.start_simvis_button = QToolButton(self.movie_controls_frame)
        self.start_simvis_button.setObjectName(u"start_simvis_button")
        self.start_simvis_button.setMinimumSize(QSize(0, 0))
        icon1 = QIcon()
        icon1.addFile(u":/material_icons/material_icons/png/skip-backward-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.start_simvis_button.setIcon(icon1)

        self.horizontalLayout_5.addWidget(self.start_simvis_button)

        self.previous_button = QToolButton(self.movie_controls_frame)
        self.previous_button.setObjectName(u"previous_button")
        self.previous_button.setMinimumSize(QSize(0, 0))
        icon2 = QIcon()
        icon2.addFile(u":/material_icons/material_icons/png/skip-previous-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.previous_button.setIcon(icon2)

        self.horizontalLayout_5.addWidget(self.previous_button)

        self.play_button = QToolButton(self.movie_controls_frame)
        self.play_button.setObjectName(u"play_button")
        self.play_button.setMinimumSize(QSize(0, 0))
        icon3 = QIcon()
        icon3.addFile(u":/material_icons/material_icons/png/play-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.play_button.setIcon(icon3)

        self.horizontalLayout_5.addWidget(self.play_button)

        self.pause_button = QToolButton(self.movie_controls_frame)
        self.pause_button.setObjectName(u"pause_button")
        self.pause_button.setMinimumSize(QSize(0, 0))
        icon4 = QIcon()
        icon4.addFile(u":/material_icons/material_icons/png/pause-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pause_button.setIcon(icon4)

        self.horizontalLayout_5.addWidget(self.pause_button)

        self.next_button = QToolButton(self.movie_controls_frame)
        self.next_button.setObjectName(u"next_button")
        self.next_button.setMinimumSize(QSize(0, 0))
        icon5 = QIcon()
        icon5.addFile(u":/material_icons/material_icons/png/skip-next-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.next_button.setIcon(icon5)

        self.horizontalLayout_5.addWidget(self.next_button)

        self.end_simvis_button = QToolButton(self.movie_controls_frame)
        self.end_simvis_button.setObjectName(u"end_simvis_button")
        self.end_simvis_button.setMinimumSize(QSize(0, 0))
        icon6 = QIcon()
        icon6.addFile(u":/material_icons/material_icons/png/skip-forward-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.end_simvis_button.setIcon(icon6)

        self.horizontalLayout_5.addWidget(self.end_simvis_button)


        self.gridLayout_3.addWidget(self.movie_controls_frame, 1, 0, 1, 2)

        self.vis_scrollArea.setWidget(self.scrollAreaWidgetContents_4)

        self.gridLayout.addWidget(self.vis_scrollArea, 1, 5, 4, 3)

        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(1)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy3)
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.import_pushButton = QPushButton(self.frame)
        self.import_pushButton.setObjectName(u"import_pushButton")
        sizePolicy4 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.import_pushButton.sizePolicy().hasHeightForWidth())
        self.import_pushButton.setSizePolicy(sizePolicy4)
        self.import_pushButton.setBaseSize(QSize(0, 0))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(12)
        self.import_pushButton.setFont(font1)
        icon7 = QIcon()
        icon7.addFile(u":/material_icons/material_icons/png/folder-arrow-down-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.import_pushButton.setIcon(icon7)

        self.horizontalLayout_7.addWidget(self.import_pushButton)

        self.view_results_pushButton = QPushButton(self.frame)
        self.view_results_pushButton.setObjectName(u"view_results_pushButton")
        self.view_results_pushButton.setEnabled(False)
        sizePolicy4.setHeightForWidth(self.view_results_pushButton.sizePolicy().hasHeightForWidth())
        self.view_results_pushButton.setSizePolicy(sizePolicy4)
        self.view_results_pushButton.setMinimumSize(QSize(0, 0))
        self.view_results_pushButton.setBaseSize(QSize(0, 0))
        self.view_results_pushButton.setFont(font1)
        icon8 = QIcon()
        icon8.addFile(u":/material_icons/material_icons/png/folder-arrow-right-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.view_results_pushButton.setIcon(icon8)

        self.horizontalLayout_7.addWidget(self.view_results_pushButton)


        self.verticalLayout.addLayout(self.horizontalLayout_7)

        self.dataAnalysis_groupBox = QGroupBox(self.frame)
        self.dataAnalysis_groupBox.setObjectName(u"dataAnalysis_groupBox")
        font2 = QFont()
        font2.setFamilies([u"Arial"])
        font2.setPointSize(12)
        font2.setBold(False)
        self.dataAnalysis_groupBox.setFont(font2)
        self.dataAnalysis_groupBox.setFlat(False)
        self.verticalLayout_2 = QVBoxLayout(self.dataAnalysis_groupBox)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.location_label = QLabel(self.dataAnalysis_groupBox)
        self.location_label.setObjectName(u"location_label")

        self.verticalLayout_2.addWidget(self.location_label)

        self.batch_lineEdit = QLineEdit(self.dataAnalysis_groupBox)
        self.batch_lineEdit.setObjectName(u"batch_lineEdit")
        sizePolicy2.setHeightForWidth(self.batch_lineEdit.sizePolicy().hasHeightForWidth())
        self.batch_lineEdit.setSizePolicy(sizePolicy2)
        self.batch_lineEdit.setStyleSheet(u"")

        self.verticalLayout_2.addWidget(self.batch_lineEdit)

        self.calculate_label = QLabel(self.dataAnalysis_groupBox)
        self.calculate_label.setObjectName(u"calculate_label")

        self.verticalLayout_2.addWidget(self.calculate_label)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.aspect_ratio_pushButton = QPushButton(self.dataAnalysis_groupBox)
        self.aspect_ratio_pushButton.setObjectName(u"aspect_ratio_pushButton")
        self.aspect_ratio_pushButton.setEnabled(False)
        sizePolicy5 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.aspect_ratio_pushButton.sizePolicy().hasHeightForWidth())
        self.aspect_ratio_pushButton.setSizePolicy(sizePolicy5)

        self.horizontalLayout_2.addWidget(self.aspect_ratio_pushButton)

        self.growth_rate_pushButton = QPushButton(self.dataAnalysis_groupBox)
        self.growth_rate_pushButton.setObjectName(u"growth_rate_pushButton")
        self.growth_rate_pushButton.setEnabled(False)
        sizePolicy5.setHeightForWidth(self.growth_rate_pushButton.sizePolicy().hasHeightForWidth())
        self.growth_rate_pushButton.setSizePolicy(sizePolicy5)

        self.horizontalLayout_2.addWidget(self.growth_rate_pushButton)


        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.plot_label = QLabel(self.dataAnalysis_groupBox)
        self.plot_label.setObjectName(u"plot_label")

        self.horizontalLayout_4.addWidget(self.plot_label)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_2)

        self.plot_browse_pushButton = QPushButton(self.dataAnalysis_groupBox)
        self.plot_browse_pushButton.setObjectName(u"plot_browse_pushButton")
        icon9 = QIcon()
        icon9.addFile(u":/material_icons/material_icons/png/file-table-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.plot_browse_pushButton.setIcon(icon9)

        self.horizontalLayout_4.addWidget(self.plot_browse_pushButton)


        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.plot_lineEdit = QLineEdit(self.dataAnalysis_groupBox)
        self.plot_lineEdit.setObjectName(u"plot_lineEdit")
        sizePolicy6 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy6.setHorizontalStretch(5)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.plot_lineEdit.sizePolicy().hasHeightForWidth())
        self.plot_lineEdit.setSizePolicy(sizePolicy6)
        self.plot_lineEdit.setStyleSheet(u"")

        self.horizontalLayout_6.addWidget(self.plot_lineEdit)

        self.plot_pushButton = QPushButton(self.dataAnalysis_groupBox)
        self.plot_pushButton.setObjectName(u"plot_pushButton")
        self.plot_pushButton.setEnabled(False)
        icon10 = QIcon()
        icon10.addFile(u":/material_icons/material_icons/png/chart-scatter-plot-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.plot_pushButton.setIcon(icon10)

        self.horizontalLayout_6.addWidget(self.plot_pushButton)


        self.verticalLayout_2.addLayout(self.horizontalLayout_6)


        self.verticalLayout.addWidget(self.dataAnalysis_groupBox)

        self.visualisation_groupBox = QGroupBox(self.frame)
        self.visualisation_groupBox.setObjectName(u"visualisation_groupBox")
        self.visualisation_groupBox.setFont(font1)
        self.verticalLayout_6 = QVBoxLayout(self.visualisation_groupBox)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.xyz_tabWidget = QTabWidget(self.visualisation_groupBox)
        self.xyz_tabWidget.setObjectName(u"xyz_tabWidget")
        self.xyz_files_tab = QWidget()
        self.xyz_files_tab.setObjectName(u"xyz_files_tab")
        self.gridLayout_2 = QGridLayout(self.xyz_files_tab)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.xyz_fname_comboBox = QComboBox(self.xyz_files_tab)
        self.xyz_fname_comboBox.setObjectName(u"xyz_fname_comboBox")
        self.xyz_fname_comboBox.setEnabled(False)
        sizePolicy7 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy7.setHorizontalStretch(1)
        sizePolicy7.setVerticalStretch(1)
        sizePolicy7.setHeightForWidth(self.xyz_fname_comboBox.sizePolicy().hasHeightForWidth())
        self.xyz_fname_comboBox.setSizePolicy(sizePolicy7)
        self.xyz_fname_comboBox.setMinimumSize(QSize(0, 0))
        font3 = QFont()
        font3.setFamilies([u".AppleSystemUIFont"])
        font3.setPointSize(13)
        font3.setKerning(True)
        self.xyz_fname_comboBox.setFont(font3)
        self.xyz_fname_comboBox.setStyleSheet(u"")

        self.gridLayout_2.addWidget(self.xyz_fname_comboBox, 1, 0, 1, 4)

        self.xyz_id_label = QLabel(self.xyz_files_tab)
        self.xyz_id_label.setObjectName(u"xyz_id_label")
        self.xyz_id_label.setEnabled(False)

        self.gridLayout_2.addWidget(self.xyz_id_label, 0, 0, 1, 1)

        self.saveframe_pushButton = QPushButton(self.xyz_files_tab)
        self.saveframe_pushButton.setObjectName(u"saveframe_pushButton")
        self.saveframe_pushButton.setEnabled(False)
        icon11 = QIcon()
        icon11.addFile(u":/material_icons/material_icons/png/content-save-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.saveframe_pushButton.setIcon(icon11)

        self.gridLayout_2.addWidget(self.saveframe_pushButton, 0, 3, 1, 1)

        self.xyz_spinBox = QSpinBox(self.xyz_files_tab)
        self.xyz_spinBox.setObjectName(u"xyz_spinBox")
        self.xyz_spinBox.setEnabled(False)
        self.xyz_spinBox.setMinimumSize(QSize(0, 0))
        self.xyz_spinBox.setStyleSheet(u"")

        self.gridLayout_2.addWidget(self.xyz_spinBox, 0, 1, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_2.addItem(self.verticalSpacer_2, 2, 0, 1, 1)

        self.xyz_tabWidget.addTab(self.xyz_files_tab, "")
        self.xyz_variables_tab = QWidget()
        self.xyz_variables_tab.setObjectName(u"xyz_variables_tab")
        self.verticalLayout_5 = QVBoxLayout(self.xyz_variables_tab)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.simulationVariablesSelectButton = QPushButton(self.xyz_variables_tab)
        self.simulationVariablesSelectButton.setObjectName(u"simulationVariablesSelectButton")
        self.simulationVariablesSelectButton.setEnabled(False)
        sizePolicy8 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy8.setHorizontalStretch(0)
        sizePolicy8.setVerticalStretch(1)
        sizePolicy8.setHeightForWidth(self.simulationVariablesSelectButton.sizePolicy().hasHeightForWidth())
        self.simulationVariablesSelectButton.setSizePolicy(sizePolicy8)
        self.simulationVariablesSelectButton.setMinimumSize(QSize(200, 0))
        font4 = QFont()
        font4.setFamilies([u"Arial"])
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setItalic(False)
        self.simulationVariablesSelectButton.setFont(font4)

        self.verticalLayout_5.addWidget(self.simulationVariablesSelectButton)

        self.simulationVariablesHeading = QLabel(self.xyz_variables_tab)
        self.simulationVariablesHeading.setObjectName(u"simulationVariablesHeading")

        self.verticalLayout_5.addWidget(self.simulationVariablesHeading)

        self.simulationVariablesSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_5.addItem(self.simulationVariablesSpacer)

        self.xyz_tabWidget.addTab(self.xyz_variables_tab, "")

        self.verticalLayout_6.addWidget(self.xyz_tabWidget)

        self.settings_pushButton = QPushButton(self.visualisation_groupBox)
        self.settings_pushButton.setObjectName(u"settings_pushButton")
        self.settings_pushButton.setEnabled(True)
        self.settings_pushButton.setMinimumSize(QSize(0, 0))
        icon12 = QIcon()
        icon12.addFile(u":/material_icons/material_icons/png/cog-custom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.settings_pushButton.setIcon(icon12)

        self.verticalLayout_6.addWidget(self.settings_pushButton)


        self.verticalLayout.addWidget(self.visualisation_groupBox)

        self.groupBox = QGroupBox(self.frame)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setFont(font1)
        self.gridLayout_4 = QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.crystal_info_formLayout = QFormLayout()
        self.crystal_info_formLayout.setObjectName(u"crystal_info_formLayout")
        self.crystal_info_formLayout.setFieldGrowthPolicy(QFormLayout.ExpandingFieldsGrow)
        self.crystal_info_formLayout.setLabelAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.crystal_info_formLayout.setFormAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.crystal_info_formLayout.setHorizontalSpacing(-1)
        self.crystal_info_formLayout.setVerticalSpacing(7)
        self.crystal_info_formLayout.setContentsMargins(10, -1, 10, -1)
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")

        self.crystal_info_formLayout.setWidget(8, QFormLayout.LabelRole, self.label_9)

        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")

        self.crystal_info_formLayout.setWidget(7, QFormLayout.LabelRole, self.label_8)

        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")

        self.crystal_info_formLayout.setWidget(6, QFormLayout.LabelRole, self.label_7)

        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")

        self.crystal_info_formLayout.setWidget(5, QFormLayout.LabelRole, self.label_6)

        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")

        self.crystal_info_formLayout.setWidget(4, QFormLayout.LabelRole, self.label_5)

        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")

        self.crystal_info_formLayout.setWidget(3, QFormLayout.LabelRole, self.label_4)

        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")

        self.crystal_info_formLayout.setWidget(2, QFormLayout.LabelRole, self.label_3)

        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")

        self.crystal_info_formLayout.setWidget(1, QFormLayout.LabelRole, self.label_2)

        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")

        self.crystal_info_formLayout.setWidget(0, QFormLayout.LabelRole, self.label)

        self.aspect1_label = QLabel(self.groupBox)
        self.aspect1_label.setObjectName(u"aspect1_label")

        self.crystal_info_formLayout.setWidget(0, QFormLayout.FieldRole, self.aspect1_label)

        self.aspect2_label = QLabel(self.groupBox)
        self.aspect2_label.setObjectName(u"aspect2_label")

        self.crystal_info_formLayout.setWidget(1, QFormLayout.FieldRole, self.aspect2_label)

        self.shape_label = QLabel(self.groupBox)
        self.shape_label.setObjectName(u"shape_label")

        self.crystal_info_formLayout.setWidget(2, QFormLayout.FieldRole, self.shape_label)

        self.savol_label = QLabel(self.groupBox)
        self.savol_label.setObjectName(u"savol_label")

        self.crystal_info_formLayout.setWidget(3, QFormLayout.FieldRole, self.savol_label)

        self.sa_label = QLabel(self.groupBox)
        self.sa_label.setObjectName(u"sa_label")

        self.crystal_info_formLayout.setWidget(4, QFormLayout.FieldRole, self.sa_label)

        self.vol_label = QLabel(self.groupBox)
        self.vol_label.setObjectName(u"vol_label")

        self.crystal_info_formLayout.setWidget(5, QFormLayout.FieldRole, self.vol_label)

        self.sg_label = QLabel(self.groupBox)
        self.sg_label.setObjectName(u"sg_label")

        self.crystal_info_formLayout.setWidget(6, QFormLayout.FieldRole, self.sg_label)

        self.uc_lengths_label = QLabel(self.groupBox)
        self.uc_lengths_label.setObjectName(u"uc_lengths_label")

        self.crystal_info_formLayout.setWidget(7, QFormLayout.FieldRole, self.uc_lengths_label)

        self.uc_angles_label = QLabel(self.groupBox)
        self.uc_angles_label.setObjectName(u"uc_angles_label")

        self.crystal_info_formLayout.setWidget(8, QFormLayout.FieldRole, self.uc_angles_label)


        self.gridLayout_4.addLayout(self.crystal_info_formLayout, 0, 0, 1, 1)


        self.verticalLayout.addWidget(self.groupBox)


        self.gridLayout.addWidget(self.frame, 1, 0, 4, 2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        font5 = QFont()
        font5.setFamilies([u"Arial"])
        font5.setPointSize(8)
        font5.setItalic(True)
        self.statusbar.setFont(font5)
        self.statusbar.setCursor(QCursor(Qt.ArrowCursor))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.xyz_tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"CrystalAspects", None))
        self.actionOpen_Simulations.setText(QCoreApplication.translate("MainWindow", u"Open Simulations", None))
        self.actionOpen_XYZs.setText(QCoreApplication.translate("MainWindow", u"Open XYZs", None))
        self.actionOpen_Outputs.setText(QCoreApplication.translate("MainWindow", u"Open Outputs", None))
        self.actionAmber.setText(QCoreApplication.translate("MainWindow", u"Amber", None))
        self.actionBlue.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
        self.actionCyan.setText(QCoreApplication.translate("MainWindow", u"Cyan", None))
        self.actionCyan_500.setText(QCoreApplication.translate("MainWindow", u"Cyan-500", None))
        self.actionLight_green.setText(QCoreApplication.translate("MainWindow", u"Light-green", None))
        self.actionPink.setText(QCoreApplication.translate("MainWindow", u"Pink", None))
        self.actionPurple.setText(QCoreApplication.translate("MainWindow", u"Purple", None))
        self.actionRed_2.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.actionTeal.setText(QCoreApplication.translate("MainWindow", u"Teal", None))
        self.actionYellow.setText(QCoreApplication.translate("MainWindow", u"Yellow", None))
        self.actionAmber_2.setText(QCoreApplication.translate("MainWindow", u"Amber", None))
        self.actionBlue_2.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
        self.actionCyan_2.setText(QCoreApplication.translate("MainWindow", u"Cyan", None))
        self.actionLight_green_2.setText(QCoreApplication.translate("MainWindow", u"Light-green", None))
        self.actionPink_2.setText(QCoreApplication.translate("MainWindow", u"Pink", None))
        self.actionPurple_2.setText(QCoreApplication.translate("MainWindow", u"Purple", None))
        self.actionRed.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.actionTeal_2.setText(QCoreApplication.translate("MainWindow", u"Teal", None))
        self.actionCyan_501.setText(QCoreApplication.translate("MainWindow", u"Cyan-500", None))
        self.actionLight_green_3.setText(QCoreApplication.translate("MainWindow", u"Light-green", None))
        self.actionPink_3.setText(QCoreApplication.translate("MainWindow", u"Pink", None))
        self.actionPurple_3.setText(QCoreApplication.translate("MainWindow", u"Purple", None))
        self.actionRed_3.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.actionTeal_3.setText(QCoreApplication.translate("MainWindow", u"Teal", None))
        self.actionYellow_2.setText(QCoreApplication.translate("MainWindow", u"Yellow", None))
        self.action_5.setText(QCoreApplication.translate("MainWindow", u"-5", None))
        self.action_4.setText(QCoreApplication.translate("MainWindow", u"-4", None))
        self.action_6.setText(QCoreApplication.translate("MainWindow", u"-3", None))
        self.action_7.setText(QCoreApplication.translate("MainWindow", u"-2", None))
        self.action_1.setText(QCoreApplication.translate("MainWindow", u"-1", None))
        self.action0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.action1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.action2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.action3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.action4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.action5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.actionDensity_2.setText(QCoreApplication.translate("MainWindow", u"Density", None))
        self.actionStyle.setText(QCoreApplication.translate("MainWindow", u"Style", None))
        self.action_8.setText(QCoreApplication.translate("MainWindow", u"-4", None))
        self.action_9.setText(QCoreApplication.translate("MainWindow", u"-3", None))
        self.action_10.setText(QCoreApplication.translate("MainWindow", u"-2", None))
        self.action_11.setText(QCoreApplication.translate("MainWindow", u"-1", None))
        self.action0_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.action1_2.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.action2_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.action3_2.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.action4_2.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.action_12.setText(QCoreApplication.translate("MainWindow", u"-3", None))
        self.action_13.setText(QCoreApplication.translate("MainWindow", u"-2", None))
        self.action_14.setText(QCoreApplication.translate("MainWindow", u"-1", None))
        self.action0_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.action1_3.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.action2_3.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.action3_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.start_simvis_button.setText("")
        self.previous_button.setText(QCoreApplication.translate("MainWindow", u"   Previous", None))
        self.play_button.setText(QCoreApplication.translate("MainWindow", u"   Play", None))
        self.pause_button.setText(QCoreApplication.translate("MainWindow", u"   Pause", None))
        self.next_button.setText(QCoreApplication.translate("MainWindow", u"   Next", None))
        self.end_simvis_button.setText(QCoreApplication.translate("MainWindow", u"   End", None))
        self.import_pushButton.setText(QCoreApplication.translate("MainWindow", u"   Import", None))
        self.view_results_pushButton.setText(QCoreApplication.translate("MainWindow", u"   View Results Directory", None))
        self.dataAnalysis_groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Data Analysis", None))
        self.location_label.setText(QCoreApplication.translate("MainWindow", u"Location", None))
        self.calculate_label.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.aspect_ratio_pushButton.setText(QCoreApplication.translate("MainWindow", u"Aspect Ratios", None))
        self.growth_rate_pushButton.setText(QCoreApplication.translate("MainWindow", u"Growth Rates", None))
        self.plot_label.setText(QCoreApplication.translate("MainWindow", u"Plotting", None))
#if QT_CONFIG(tooltip)
        self.plot_browse_pushButton.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.plot_browse_pushButton.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.plot_browse_pushButton.setText(QCoreApplication.translate("MainWindow", u"Import CSV for Plotting", None))
#if QT_CONFIG(tooltip)
        self.plot_pushButton.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.plot_pushButton.setText(QCoreApplication.translate("MainWindow", u"   Plot", None))
        self.visualisation_groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Visualisation", None))
        self.xyz_id_label.setText(QCoreApplication.translate("MainWindow", u"XYZ ID: ", None))
#if QT_CONFIG(statustip)
        self.saveframe_pushButton.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.saveframe_pushButton.setText(QCoreApplication.translate("MainWindow", u"Save Frame", None))
        self.xyz_tabWidget.setTabText(self.xyz_tabWidget.indexOf(self.xyz_files_tab), QCoreApplication.translate("MainWindow", u"Files", None))
        self.simulationVariablesSelectButton.setText(QCoreApplication.translate("MainWindow", u"Select Summary File", None))
        self.simulationVariablesHeading.setText(QCoreApplication.translate("MainWindow", u"Simulation Variables", None))
        self.xyz_tabWidget.setTabText(self.xyz_tabWidget.indexOf(self.xyz_variables_tab), QCoreApplication.translate("MainWindow", u"Variables", None))
#if QT_CONFIG(statustip)
        self.settings_pushButton.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.settings_pushButton.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Crystal Information", None))
#if QT_CONFIG(tooltip)
        self.label_9.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Unit cell angles (<span style=\" font-weight:600;\">\u03b1 \u03b2 \u03b3</span>)</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_8.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Unit cell lengths(<b>a b c</b>)", None))
#if QT_CONFIG(tooltip)
        self.label_7.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Space Group", None))
#if QT_CONFIG(tooltip)
        self.label_6.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Volume (<span style=\" font-weight:600;\">nm</span><span style=\" font-weight:600; vertical-align:super;\">3</span>)</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_5.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Surface Area (<span style=\" font-weight:600;\">nm</span><span style=\" font-weight:600; vertical-align:super;\">2</span>)</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.label_4.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Surface Area : Volume", None))
#if QT_CONFIG(tooltip)
        self.label_3.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"General Shape", None))
#if QT_CONFIG(tooltip)
        self.label_2.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Aspect Ratio M:L", None))
#if QT_CONFIG(tooltip)
        self.label.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label.setText(QCoreApplication.translate("MainWindow", u"Aspect Ratio S:M", None))
        self.aspect1_label.setText("")
        self.aspect2_label.setText("")
        self.shape_label.setText("")
        self.savol_label.setText("")
        self.sa_label.setText("")
        self.vol_label.setText("")
        self.sg_label.setText("")
        self.uc_lengths_label.setText("")
        self.uc_angles_label.setText("")
    # retranslateUi

