# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InputWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1084, 836)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("../../../CrystalGrower-DataProcessor/GUI/icon.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_normal = QtWidgets.QWidget()
        self.tab_normal.setObjectName("tab_normal")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_normal)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_normal)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 497, 664))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.normalMode_toolBox = QtWidgets.QToolBox(self.scrollAreaWidgetContents_4)
        self.normalMode_toolBox.setMinimumSize(QtCore.QSize(450, 500))
        self.normalMode_toolBox.setObjectName("normalMode_toolBox")
        self.widget = QtWidgets.QWidget()
        self.widget.setGeometry(QtCore.QRect(0, 0, 471, 506))
        self.widget.setObjectName("widget")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 445, 480))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.facet_gBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.facet_gBox.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.facet_gBox.setFont(font)
        self.facet_gBox.setToolTip("")
        self.facet_gBox.setObjectName("facet_gBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.facet_gBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_8.addWidget(self.facet_gBox, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_22.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.normalMode_toolBox.addItem(self.widget, "")
        self.normal_calc_page = QtWidgets.QWidget()
        self.normal_calc_page.setGeometry(QtCore.QRect(0, 0, 473, 491))
        self.normal_calc_page.setObjectName("normal_calc_page")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.normal_calc_page)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.options_gBox = QtWidgets.QFrame(self.normal_calc_page)
        self.options_gBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.options_gBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.options_gBox.setObjectName("options_gBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.options_gBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.growthRate_checkBox = QtWidgets.QCheckBox(self.options_gBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.growthRate_checkBox.setFont(font)
        self.growthRate_checkBox.setChecked(False)
        self.growthRate_checkBox.setObjectName("growthRate_checkBox")
        self.verticalLayout_8.addWidget(self.growthRate_checkBox)
        self.sa_vol_checkBox = QtWidgets.QCheckBox(self.options_gBox)
        self.sa_vol_checkBox.setObjectName("sa_vol_checkBox")
        self.verticalLayout_8.addWidget(self.sa_vol_checkBox)
        self.aspectRatio_checkBox = QtWidgets.QCheckBox(self.options_gBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.aspectRatio_checkBox.setFont(font)
        self.aspectRatio_checkBox.setObjectName("aspectRatio_checkBox")
        self.verticalLayout_8.addWidget(self.aspectRatio_checkBox)
        self.aspect_options_frame = QtWidgets.QFrame(self.options_gBox)
        self.aspect_options_frame.setEnabled(True)
        self.aspect_options_frame.setMinimumSize(QtCore.QSize(423, 0))
        self.aspect_options_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.aspect_options_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.aspect_options_frame.setObjectName("aspect_options_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.aspect_options_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pca_checkBox = QtWidgets.QCheckBox(self.aspect_options_frame)
        self.pca_checkBox.setObjectName("pca_checkBox")
        self.verticalLayout_7.addWidget(self.pca_checkBox)
        self.cda_checkBox = QtWidgets.QCheckBox(self.aspect_options_frame)
        self.cda_checkBox.setObjectName("cda_checkBox")
        self.verticalLayout_7.addWidget(self.cda_checkBox)
        self.aspect_directions_HLayout = QtWidgets.QHBoxLayout()
        self.aspect_directions_HLayout.setObjectName("aspect_directions_HLayout")
        self.long_facet = QtWidgets.QComboBox(self.aspect_options_frame)
        self.long_facet.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.long_facet.sizePolicy().hasHeightForWidth())
        self.long_facet.setSizePolicy(sizePolicy)
        self.long_facet.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.long_facet.setFont(font)
        self.long_facet.setObjectName("long_facet")
        self.aspect_directions_HLayout.addWidget(self.long_facet)
        self.ratio_label1 = QtWidgets.QLabel(self.aspect_options_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ratio_label1.setFont(font)
        self.ratio_label1.setAlignment(QtCore.Qt.AlignCenter)
        self.ratio_label1.setObjectName("ratio_label1")
        self.aspect_directions_HLayout.addWidget(self.ratio_label1)
        self.medium_facet = QtWidgets.QComboBox(self.aspect_options_frame)
        self.medium_facet.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.medium_facet.sizePolicy().hasHeightForWidth())
        self.medium_facet.setSizePolicy(sizePolicy)
        self.medium_facet.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.medium_facet.setFont(font)
        self.medium_facet.setObjectName("medium_facet")
        self.aspect_directions_HLayout.addWidget(self.medium_facet)
        self.ratio_label2 = QtWidgets.QLabel(self.aspect_options_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ratio_label2.setFont(font)
        self.ratio_label2.setAlignment(QtCore.Qt.AlignCenter)
        self.ratio_label2.setObjectName("ratio_label2")
        self.aspect_directions_HLayout.addWidget(self.ratio_label2)
        self.short_facet = QtWidgets.QComboBox(self.aspect_options_frame)
        self.short_facet.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.short_facet.sizePolicy().hasHeightForWidth())
        self.short_facet.setSizePolicy(sizePolicy)
        self.short_facet.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.short_facet.setFont(font)
        self.short_facet.setObjectName("short_facet")
        self.aspect_directions_HLayout.addWidget(self.short_facet)
        self.verticalLayout_7.addLayout(self.aspect_directions_HLayout)
        self.aspect_ranges_HLayout = QtWidgets.QHBoxLayout()
        self.aspect_ranges_HLayout.setObjectName("aspect_ranges_HLayout")
        self.aspect_range_checkBox = QtWidgets.QCheckBox(self.aspect_options_frame)
        self.aspect_range_checkBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.aspect_range_checkBox.sizePolicy().hasHeightForWidth()
        )
        self.aspect_range_checkBox.setSizePolicy(sizePolicy)
        self.aspect_range_checkBox.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.aspect_range_checkBox.setFont(font)
        self.aspect_range_checkBox.setObjectName("aspect_range_checkBox")
        self.aspect_ranges_HLayout.addWidget(self.aspect_range_checkBox)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.aspect_ranges_HLayout.addItem(spacerItem)
        self.lm_range_input = QtWidgets.QLineEdit(self.aspect_options_frame)
        self.lm_range_input.setEnabled(False)
        self.lm_range_input.setMinimumSize(QtCore.QSize(50, 25))
        self.lm_range_input.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lm_range_input.setFont(font)
        self.lm_range_input.setObjectName("lm_range_input")
        self.aspect_ranges_HLayout.addWidget(self.lm_range_input)
        self.lm_plusminus_label = QtWidgets.QLabel(self.aspect_options_frame)
        self.lm_plusminus_label.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lm_plusminus_label.setFont(font)
        self.lm_plusminus_label.setObjectName("lm_plusminus_label")
        self.aspect_ranges_HLayout.addWidget(self.lm_plusminus_label)
        self.lm_spinBox = QtWidgets.QSpinBox(self.aspect_options_frame)
        self.lm_spinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lm_spinBox.sizePolicy().hasHeightForWidth())
        self.lm_spinBox.setSizePolicy(sizePolicy)
        self.lm_spinBox.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lm_spinBox.setFont(font)
        self.lm_spinBox.setObjectName("lm_spinBox")
        self.aspect_ranges_HLayout.addWidget(self.lm_spinBox)
        self.lm_percent_label = QtWidgets.QLabel(self.aspect_options_frame)
        self.lm_percent_label.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lm_percent_label.setFont(font)
        self.lm_percent_label.setObjectName("lm_percent_label")
        self.aspect_ranges_HLayout.addWidget(self.lm_percent_label)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.aspect_ranges_HLayout.addItem(spacerItem1)
        self.ms_range_input = QtWidgets.QLineEdit(self.aspect_options_frame)
        self.ms_range_input.setEnabled(False)
        self.ms_range_input.setMinimumSize(QtCore.QSize(50, 25))
        self.ms_range_input.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ms_range_input.setFont(font)
        self.ms_range_input.setObjectName("ms_range_input")
        self.aspect_ranges_HLayout.addWidget(self.ms_range_input)
        self.ms_plusminus_label = QtWidgets.QLabel(self.aspect_options_frame)
        self.ms_plusminus_label.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ms_plusminus_label.setFont(font)
        self.ms_plusminus_label.setObjectName("ms_plusminus_label")
        self.aspect_ranges_HLayout.addWidget(self.ms_plusminus_label)
        self.ms_spinBox = QtWidgets.QSpinBox(self.aspect_options_frame)
        self.ms_spinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ms_spinBox.sizePolicy().hasHeightForWidth())
        self.ms_spinBox.setSizePolicy(sizePolicy)
        self.ms_spinBox.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ms_spinBox.setFont(font)
        self.ms_spinBox.setObjectName("ms_spinBox")
        self.aspect_ranges_HLayout.addWidget(self.ms_spinBox)
        self.ms_percent_label = QtWidgets.QLabel(self.aspect_options_frame)
        self.ms_percent_label.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ms_percent_label.setFont(font)
        self.ms_percent_label.setObjectName("ms_percent_label")
        self.aspect_ranges_HLayout.addWidget(self.ms_percent_label)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.aspect_ranges_HLayout.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.aspect_ranges_HLayout)
        self.ladderLayout = QtWidgets.QHBoxLayout()
        self.ladderLayout.setObjectName("ladderLayout")
        self.count_checkBox = QtWidgets.QCheckBox(self.aspect_options_frame)
        self.count_checkBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.count_checkBox.sizePolicy().hasHeightForWidth()
        )
        self.count_checkBox.setSizePolicy(sizePolicy)
        self.count_checkBox.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.count_checkBox.setFont(font)
        self.count_checkBox.setObjectName("count_checkBox")
        self.ladderLayout.addWidget(self.count_checkBox)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.ladderLayout.addItem(spacerItem3)
        self.count_range = QtWidgets.QLineEdit(self.aspect_options_frame)
        self.count_range.setEnabled(True)
        self.count_range.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.count_range.setFont(font)
        self.count_range.setObjectName("count_range")
        self.ladderLayout.addWidget(self.count_range)
        self.count_plusminus_label = QtWidgets.QLabel(self.aspect_options_frame)
        self.count_plusminus_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.count_plusminus_label.sizePolicy().hasHeightForWidth()
        )
        self.count_plusminus_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.count_plusminus_label.setFont(font)
        self.count_plusminus_label.setObjectName("count_plusminus_label")
        self.ladderLayout.addWidget(self.count_plusminus_label)
        self.count_spinBox = QtWidgets.QSpinBox(self.aspect_options_frame)
        self.count_spinBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.count_spinBox.sizePolicy().hasHeightForWidth()
        )
        self.count_spinBox.setSizePolicy(sizePolicy)
        self.count_spinBox.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.count_spinBox.setFont(font)
        self.count_spinBox.setObjectName("count_spinBox")
        self.ladderLayout.addWidget(self.count_spinBox)
        self.count_percent_label = QtWidgets.QLabel(self.aspect_options_frame)
        self.count_percent_label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.count_percent_label.setFont(font)
        self.count_percent_label.setObjectName("count_percent_label")
        self.ladderLayout.addWidget(self.count_percent_label)
        self.verticalLayout_7.addLayout(self.ladderLayout)
        self.verticalLayout_8.addWidget(self.aspect_options_frame)
        self.plot_checkBox = QtWidgets.QCheckBox(self.options_gBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.plot_checkBox.setFont(font)
        self.plot_checkBox.setObjectName("plot_checkBox")
        self.verticalLayout_8.addWidget(self.plot_checkBox)
        self.gridLayout_24.addWidget(self.options_gBox, 0, 0, 1, 1)
        self.normalMode_toolBox.addItem(self.normal_calc_page, "")
        self.normal_plotting_page = QtWidgets.QWidget()
        self.normal_plotting_page.setGeometry(QtCore.QRect(0, 0, 471, 506))
        self.normal_plotting_page.setObjectName("normal_plotting_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.normal_plotting_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plotting_gBox = QtWidgets.QGroupBox(self.normal_plotting_page)
        self.plotting_gBox.setTitle("")
        self.plotting_gBox.setObjectName("plotting_gBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.plotting_gBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout_3.addItem(spacerItem4, 10, 0, 1, 1)
        self.plot_SAVAR_button = QtWidgets.QPushButton(self.plotting_gBox)
        self.plot_SAVAR_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.plot_SAVAR_button.setFont(font)
        self.plot_SAVAR_button.setObjectName("plot_SAVAR_button")
        self.gridLayout_3.addWidget(self.plot_SAVAR_button, 8, 0, 1, 1)
        self.plot_SA_button = QtWidgets.QPushButton(self.plotting_gBox)
        self.plot_SA_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.plot_SA_button.setFont(font)
        self.plot_SA_button.setObjectName("plot_SA_button")
        self.gridLayout_3.addWidget(self.plot_SA_button, 3, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.ar_csv_label = QtWidgets.QLabel(self.plotting_gBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ar_csv_label.setFont(font)
        self.ar_csv_label.setObjectName("ar_csv_label")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.ar_csv_label
        )
        self.ar_lineEdit = QtWidgets.QLineEdit(self.plotting_gBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ar_lineEdit.setFont(font)
        self.ar_lineEdit.setObjectName("ar_lineEdit")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.ar_lineEdit
        )
        self.ar_browse_button = QtWidgets.QPushButton(self.plotting_gBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ar_browse_button.setFont(font)
        self.ar_browse_button.setObjectName("ar_browse_button")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.ar_browse_button
        )
        self.savar_csv_label = QtWidgets.QLabel(self.plotting_gBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.savar_csv_label.setFont(font)
        self.savar_csv_label.setObjectName("savar_csv_label")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.savar_csv_label
        )
        self.SAVAR_lineEdit = QtWidgets.QLineEdit(self.plotting_gBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SAVAR_lineEdit.setFont(font)
        self.SAVAR_lineEdit.setObjectName("SAVAR_lineEdit")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.SAVAR_lineEdit
        )
        self.SAVAR_browse_button = QtWidgets.QPushButton(self.plotting_gBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SAVAR_browse_button.setFont(font)
        self.SAVAR_browse_button.setObjectName("SAVAR_browse_button")
        self.formLayout_2.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.SAVAR_browse_button
        )
        self.GrowthRate_browse_button = QtWidgets.QPushButton(self.plotting_gBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.GrowthRate_browse_button.setFont(font)
        self.GrowthRate_browse_button.setObjectName("GrowthRate_browse_button")
        self.formLayout_2.setWidget(
            8, QtWidgets.QFormLayout.FieldRole, self.GrowthRate_browse_button
        )
        self.GrowthRate_lineEdit = QtWidgets.QLineEdit(self.plotting_gBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.GrowthRate_lineEdit.setFont(font)
        self.GrowthRate_lineEdit.setObjectName("GrowthRate_lineEdit")
        self.formLayout_2.setWidget(
            7, QtWidgets.QFormLayout.FieldRole, self.GrowthRate_lineEdit
        )
        self.growthrate_cs_label = QtWidgets.QLabel(self.plotting_gBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.growthrate_cs_label.setFont(font)
        self.growthrate_cs_label.setObjectName("growthrate_cs_label")
        self.formLayout_2.setWidget(
            7, QtWidgets.QFormLayout.LabelRole, self.growthrate_cs_label
        )
        self.gridLayout_3.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.plot_AR_button = QtWidgets.QPushButton(self.plotting_gBox)
        self.plot_AR_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.plot_AR_button.setFont(font)
        self.plot_AR_button.setObjectName("plot_AR_button")
        self.gridLayout_3.addWidget(self.plot_AR_button, 1, 0, 1, 1)
        self.plot_vol_button = QtWidgets.QPushButton(self.plotting_gBox)
        self.plot_vol_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.plot_vol_button.setFont(font)
        self.plot_vol_button.setObjectName("plot_vol_button")
        self.gridLayout_3.addWidget(self.plot_vol_button, 7, 0, 1, 1)
        self.plot_GrowthRate_button = QtWidgets.QPushButton(self.plotting_gBox)
        self.plot_GrowthRate_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.plot_GrowthRate_button.setFont(font)
        self.plot_GrowthRate_button.setObjectName("plot_GrowthRate_button")
        self.gridLayout_3.addWidget(self.plot_GrowthRate_button, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.plotting_gBox, 1, 0, 1, 1)
        self.normalMode_toolBox.addItem(self.normal_plotting_page, "")
        self.horizontalLayout_7.addWidget(self.normalMode_toolBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.run_calc_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.run_calc_button.sizePolicy().hasHeightForWidth()
        )
        self.run_calc_button.setSizePolicy(sizePolicy)
        self.run_calc_button.setMinimumSize(QtCore.QSize(170, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.run_calc_button.setFont(font)
        self.run_calc_button.setStyleSheet("")
        self.run_calc_button.setObjectName("run_calc_button")
        self.horizontalLayout_4.addWidget(self.run_calc_button)
        self.reset_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_button.sizePolicy().hasHeightForWidth())
        self.reset_button.setSizePolicy(sizePolicy)
        self.reset_button.setMinimumSize(QtCore.QSize(170, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.reset_button.setFont(font)
        self.reset_button.setStyleSheet("")
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout_4.addWidget(self.reset_button)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_2.addWidget(self.scrollArea_3)
        self.optionButtons_HLayout = QtWidgets.QFrame(self.tab_normal)
        self.optionButtons_HLayout.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.optionButtons_HLayout.setFrameShadow(QtWidgets.QFrame.Plain)
        self.optionButtons_HLayout.setLineWidth(0)
        self.optionButtons_HLayout.setObjectName("optionButtons_HLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.optionButtons_HLayout)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2.addWidget(self.optionButtons_HLayout)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.output_label = QtWidgets.QLabel(self.tab_normal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.output_label.setFont(font)
        self.output_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.output_label.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing
        )
        self.output_label.setObjectName("output_label")
        self.verticalLayout_11.addWidget(self.output_label, 0, QtCore.Qt.AlignTop)
        self.output_textBox = QtWidgets.QTextEdit(self.tab_normal)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.output_textBox.sizePolicy().hasHeightForWidth()
        )
        self.output_textBox.setSizePolicy(sizePolicy)
        self.output_textBox.setMinimumSize(QtCore.QSize(300, 535))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.output_textBox.setFont(font)
        self.output_textBox.setStyleSheet(
            "background-color: rgb(58, 64, 85);\n" "color: rgb(255, 255, 255);"
        )
        self.output_textBox.setReadOnly(True)
        self.output_textBox.setObjectName("output_textBox")
        self.verticalLayout_11.addWidget(self.output_textBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.tab_normal, "")
        self.tab_maps = QtWidgets.QWidget()
        self.tab_maps.setObjectName("tab_maps")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_maps)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.summary_file_label = QtWidgets.QLabel(self.tab_maps)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.summary_file_label.setFont(font)
        self.summary_file_label.setObjectName("summary_file_label")
        self.gridLayout_12.addWidget(self.summary_file_label, 1, 0, 1, 1)
        self.select_summary_map_button = QtWidgets.QPushButton(self.tab_maps)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.select_summary_map_button.setFont(font)
        self.select_summary_map_button.setObjectName("select_summary_map_button")
        self.gridLayout_12.addWidget(self.select_summary_map_button, 1, 1, 1, 1)
        self.aspects_ouput_label = QtWidgets.QLabel(self.tab_maps)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.aspects_ouput_label.setFont(font)
        self.aspects_ouput_label.setObjectName("aspects_ouput_label")
        self.gridLayout_12.addWidget(self.aspects_ouput_label, 2, 0, 1, 1)
        self.select_output_button1 = QtWidgets.QPushButton(self.tab_maps)
        self.select_output_button1.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.select_output_button1.setFont(font)
        self.select_output_button1.setObjectName("select_output_button1")
        self.gridLayout_12.addWidget(self.select_output_button1, 2, 1, 1, 1)
        self.manual_entry_label = QtWidgets.QLabel(self.tab_maps)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.manual_entry_label.setFont(font)
        self.manual_entry_label.setObjectName("manual_entry_label")
        self.gridLayout_12.addWidget(self.manual_entry_label, 3, 0, 1, 1)
        self.manual_entry_button = QtWidgets.QPushButton(self.tab_maps)
        self.manual_entry_button.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.manual_entry_button.setFont(font)
        self.manual_entry_button.setObjectName("manual_entry_button")
        self.gridLayout_12.addWidget(self.manual_entry_button, 3, 1, 1, 1)
        self.scrollArea_8 = QtWidgets.QScrollArea(self.tab_maps)
        self.scrollArea_8.setMinimumSize(QtCore.QSize(0, 100))
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName("scrollArea_8")
        self.scrollAreaWidgetContents_10 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_10.setGeometry(QtCore.QRect(0, 0, 685, 98))
        self.scrollAreaWidgetContents_10.setObjectName("scrollAreaWidgetContents_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.output_textBox_3 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_10)
        self.output_textBox_3.setStyleSheet(
            "background-color: rgb(58, 64, 85);\n" "color: rgb(255, 255, 255);"
        )
        self.output_textBox_3.setObjectName("output_textBox_3")
        self.gridLayout_13.addWidget(self.output_textBox_3, 0, 0, 1, 1)
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_10)
        self.gridLayout_12.addWidget(self.scrollArea_8, 1, 2, 3, 1)
        self.verticalLayout.addLayout(self.gridLayout_12)
        self.generate_map_button = QtWidgets.QPushButton(self.tab_maps)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.generate_map_button.setFont(font)
        self.generate_map_button.setObjectName("generate_map_button")
        self.verticalLayout.addWidget(self.generate_map_button)
        self.map_scrollArea = QtWidgets.QScrollArea(self.tab_maps)
        self.map_scrollArea.setWidgetResizable(True)
        self.map_scrollArea.setObjectName("map_scrollArea")
        self.scrollAreaWidgetContents_9 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 1026, 502))
        self.scrollAreaWidgetContents_9.setObjectName("scrollAreaWidgetContents_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.map_Label = QtWidgets.QLabel(self.scrollAreaWidgetContents_9)
        self.map_Label.setText("")
        self.map_Label.setScaledContents(True)
        self.map_Label.setObjectName("map_Label")
        self.gridLayout_11.addWidget(self.map_Label, 0, 0, 1, 1)
        self.map_scrollArea.setWidget(self.scrollAreaWidgetContents_9)
        self.verticalLayout.addWidget(self.map_scrollArea)
        self.gridLayout_7.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_maps, "")
        self.tab_3d = QtWidgets.QWidget()
        self.tab_3d.setObjectName("tab_3d")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_3d)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.vis_vLayout_6 = QtWidgets.QGridLayout()
        self.vis_vLayout_6.setObjectName("vis_vLayout_6")
        self.vis_vLayout_2 = QtWidgets.QGridLayout()
        self.vis_vLayout_2.setObjectName("vis_vLayout_2")
        self.vis_vLayout_4 = QtWidgets.QGridLayout()
        self.vis_vLayout_4.setObjectName("vis_vLayout_4")
        self.vis_scrollArea = QtWidgets.QScrollArea(self.tab_3d)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.vis_scrollArea.sizePolicy().hasHeightForWidth()
        )
        self.vis_scrollArea.setSizePolicy(sizePolicy)
        self.vis_scrollArea.setWidgetResizable(True)
        self.vis_scrollArea.setObjectName("vis_scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 761, 658))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gl_vLayout = QtWidgets.QVBoxLayout()
        self.gl_vLayout.setSpacing(0)
        self.gl_vLayout.setObjectName("gl_vLayout")
        self.verticalLayout_3.addLayout(self.gl_vLayout)
        self.vis_scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.vis_vLayout_4.addWidget(self.vis_scrollArea, 1, 2, 5, 2)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab_3d)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_5.sizePolicy().hasHeightForWidth())
        self.scrollArea_5.setSizePolicy(sizePolicy)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 249, 658))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.ThreeD_toolBox = QtWidgets.QToolBox(self.scrollAreaWidgetContents_5)
        self.ThreeD_toolBox.setObjectName("ThreeD_toolBox")
        self.variables_page = QtWidgets.QWidget()
        self.variables_page.setGeometry(QtCore.QRect(0, 0, 225, 544))
        self.variables_page.setObjectName("variables_page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.variables_page)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.select_summary_slider_button = QtWidgets.QPushButton(self.variables_page)
        self.select_summary_slider_button.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.select_summary_slider_button.setFont(font)
        self.select_summary_slider_button.setObjectName("select_summary_slider_button")
        self.verticalLayout_10.addWidget(self.select_summary_slider_button)
        self.EVariable_title_label_2 = QtWidgets.QLabel(self.variables_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.EVariable_title_label_2.setFont(font)
        self.EVariable_title_label_2.setObjectName("EVariable_title_label_2")
        self.verticalLayout_10.addWidget(self.EVariable_title_label_2)
        self.E_variables_layout = QtWidgets.QGridLayout()
        self.E_variables_layout.setObjectName("E_variables_layout")
        self.verticalLayout_10.addLayout(self.E_variables_layout)
        self.output_textBox_4 = QtWidgets.QTextEdit(self.variables_page)
        self.output_textBox_4.setStyleSheet(
            "background-color: rgb(58, 64, 85);\n" "color: rgb(255, 255, 255);"
        )
        self.output_textBox_4.setObjectName("output_textBox_4")
        self.verticalLayout_10.addWidget(self.output_textBox_4)
        self.ThreeD_toolBox.addItem(self.variables_page, "")
        self.vis_options_page = QtWidgets.QWidget()
        self.vis_options_page.setGeometry(QtCore.QRect(0, 0, 95, 95))
        self.vis_options_page.setObjectName("vis_options_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.vis_options_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.vis_options_scrollArea = QtWidgets.QScrollArea(self.vis_options_page)
        self.vis_options_scrollArea.setWidgetResizable(True)
        self.vis_options_scrollArea.setObjectName("vis_options_scrollArea")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 124, 406))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_7)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.vis_vLayout_9 = QtWidgets.QVBoxLayout()
        self.vis_vLayout_9.setObjectName("vis_vLayout_9")
        self.point_type_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.point_type_label.setFont(font)
        self.point_type_label.setObjectName("point_type_label")
        self.vis_vLayout_9.addWidget(self.point_type_label)
        self.pointtype_comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_7)
        self.pointtype_comboBox.setObjectName("pointtype_comboBox")
        self.vis_vLayout_9.addWidget(self.pointtype_comboBox)
        self.display_options_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.display_options_label.setFont(font)
        self.display_options_label.setObjectName("display_options_label")
        self.vis_vLayout_9.addWidget(self.display_options_label)
        self.vis_vLayout_10 = QtWidgets.QFormLayout()
        self.vis_vLayout_10.setObjectName("vis_vLayout_10")
        self.zoom_slider = QtWidgets.QSlider(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_slider.sizePolicy().hasHeightForWidth())
        self.zoom_slider.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.zoom_slider.setFont(font)
        self.zoom_slider.setOrientation(QtCore.Qt.Horizontal)
        self.zoom_slider.setObjectName("zoom_slider")
        self.vis_vLayout_10.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.zoom_slider
        )
        self.point_slider = QtWidgets.QSlider(self.scrollAreaWidgetContents_7)
        self.point_slider.setOrientation(QtCore.Qt.Horizontal)
        self.point_slider.setObjectName("point_slider")
        self.vis_vLayout_10.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.point_slider
        )
        self.brightness_slider = QtWidgets.QSlider(self.scrollAreaWidgetContents_7)
        self.brightness_slider.setMaximum(100)
        self.brightness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.brightness_slider.setObjectName("brightness_slider")
        self.vis_vLayout_10.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.brightness_slider
        )
        self.resolution_slider = QtWidgets.QSlider(self.scrollAreaWidgetContents_7)
        self.resolution_slider.setOrientation(QtCore.Qt.Horizontal)
        self.resolution_slider.setObjectName("resolution_slider")
        self.vis_vLayout_10.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.resolution_slider
        )
        self.zoom_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.zoom_label.setObjectName("zoom_label")
        self.vis_vLayout_10.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.zoom_label
        )
        self.pointsize_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.pointsize_label.setObjectName("pointsize_label")
        self.vis_vLayout_10.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.pointsize_label
        )
        self.brightness_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.brightness_label.setObjectName("brightness_label")
        self.vis_vLayout_10.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.brightness_label
        )
        self.resolution_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.resolution_label.setObjectName("resolution_label")
        self.vis_vLayout_10.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.resolution_label
        )
        self.vis_vLayout_9.addLayout(self.vis_vLayout_10)
        self.colour_mode_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.colour_mode_label.setFont(font)
        self.colour_mode_label.setObjectName("colour_mode_label")
        self.vis_vLayout_9.addWidget(self.colour_mode_label)
        self.colourmode_comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_7)
        self.colourmode_comboBox.setObjectName("colourmode_comboBox")
        self.vis_vLayout_9.addWidget(self.colourmode_comboBox)
        self.colour_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.colour_label.setFont(font)
        self.colour_label.setObjectName("colour_label")
        self.vis_vLayout_9.addWidget(self.colour_label)
        self.colour_comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_7)
        self.colour_comboBox.setObjectName("colour_comboBox")
        self.vis_vLayout_9.addWidget(self.colour_comboBox)
        self.colour_label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.colour_label_2.setFont(font)
        self.colour_label_2.setObjectName("colour_label_2")
        self.vis_vLayout_9.addWidget(self.colour_label_2)
        self.bgcolour_comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_7)
        self.bgcolour_comboBox.setObjectName("bgcolour_comboBox")
        self.vis_vLayout_9.addWidget(self.bgcolour_comboBox)
        spacerItem5 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.vis_vLayout_9.addItem(spacerItem5)
        self.gridLayout_15.addLayout(self.vis_vLayout_9, 0, 0, 1, 1)
        self.vis_options_scrollArea.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_5.addWidget(self.vis_options_scrollArea)
        self.ThreeD_toolBox.addItem(self.vis_options_page, "")
        self.convexhull_page = QtWidgets.QWidget()
        self.convexhull_page.setGeometry(QtCore.QRect(0, 0, 139, 74))
        self.convexhull_page.setObjectName("convexhull_page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.convexhull_page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.start_3dcalc_button = QtWidgets.QPushButton(self.convexhull_page)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.start_3dcalc_button.sizePolicy().hasHeightForWidth()
        )
        self.start_3dcalc_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.start_3dcalc_button.setFont(font)
        self.start_3dcalc_button.setObjectName("start_3dcalc_button")
        self.verticalLayout_9.addWidget(self.start_3dcalc_button)
        self.stop_3dcalc_button = QtWidgets.QPushButton(self.convexhull_page)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.stop_3dcalc_button.sizePolicy().hasHeightForWidth()
        )
        self.stop_3dcalc_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.stop_3dcalc_button.setFont(font)
        self.stop_3dcalc_button.setObjectName("stop_3dcalc_button")
        self.verticalLayout_9.addWidget(self.stop_3dcalc_button)
        self.ThreeD_toolBox.addItem(self.convexhull_page, "")
        self.gridLayout_10.addWidget(self.ThreeD_toolBox, 0, 0, 1, 1)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.vis_vLayout_4.addWidget(self.scrollArea_5, 1, 0, 5, 1)
        self.vis_vLayout_2.addLayout(self.vis_vLayout_4, 1, 0, 1, 1)
        self.vis_vLayout_6.addLayout(self.vis_vLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_8.addLayout(self.vis_vLayout_6)
        self.tabWidget.addTab(self.tab_3d, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setStyleSheet(
            "QProgressBar {\n"
            "    background-color: rgb(213, 215, 255);\n"
            "    color: rgb(0, 0, 127);\n"
            "    border-style: none;\n"
            "    border-radius: 10px;\n"
            "    text-align: center;\n"
            "}\n"
            "QProgressBar::chunk{\n"
            "    border-radius: 10px;\n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.489, stop:0 rgba(255, 170, 255, 255), stop:1 rgba(185, 135, 255, 255));\n"
            "}"
        )
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 1, 1, 1)
        self.vis_vLayout_3 = QtWidgets.QHBoxLayout()
        self.vis_vLayout_3.setObjectName("vis_vLayout_3")
        self.simFolder_Button = QtWidgets.QPushButton(self.centralwidget)
        self.simFolder_Button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.simFolder_Button.sizePolicy().hasHeightForWidth()
        )
        self.simFolder_Button.setSizePolicy(sizePolicy)
        self.simFolder_Button.setMinimumSize(QtCore.QSize(170, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.simFolder_Button.setFont(font)
        self.simFolder_Button.setStyleSheet("")
        self.simFolder_Button.setObjectName("simFolder_Button")
        self.vis_vLayout_3.addWidget(self.simFolder_Button, 0, QtCore.Qt.AlignLeft)
        self.outFolder_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.outFolder_Button.sizePolicy().hasHeightForWidth()
        )
        self.outFolder_Button.setSizePolicy(sizePolicy)
        self.outFolder_Button.setMinimumSize(QtCore.QSize(170, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.outFolder_Button.setFont(font)
        self.outFolder_Button.setStyleSheet("")
        self.outFolder_Button.setObjectName("outFolder_Button")
        self.vis_vLayout_3.addWidget(self.outFolder_Button, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.vis_vLayout_3, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setItalic(True)
        self.statusbar.setFont(font)
        self.statusbar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.normalMode_toolBox.setCurrentIndex(0)
        self.ThreeD_toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CrystalAspects"))
        self.facet_gBox.setTitle(_translate("MainWindow", "Crystal Directions"))
        self.normalMode_toolBox.setItemText(
            self.normalMode_toolBox.indexOf(self.widget),
            _translate("MainWindow", "Select Directions"),
        )
        self.growthRate_checkBox.setText(_translate("MainWindow", "Growth Rate"))
        self.sa_vol_checkBox.setText(_translate("MainWindow", "Surface Area : Volume"))
        self.aspectRatio_checkBox.setText(_translate("MainWindow", "Aspect Ratio"))
        self.pca_checkBox.setText(_translate("MainWindow", "PCA"))
        self.cda_checkBox.setText(_translate("MainWindow", "CDA"))
        self.ratio_label1.setText(_translate("MainWindow", ":"))
        self.ratio_label2.setText(_translate("MainWindow", ":"))
        self.aspect_range_checkBox.setText(_translate("MainWindow", "Range"))
        self.lm_plusminus_label.setText(_translate("MainWindow", "+/-"))
        self.lm_percent_label.setText(_translate("MainWindow", "%"))
        self.ms_plusminus_label.setText(_translate("MainWindow", "+/-"))
        self.ms_percent_label.setText(_translate("MainWindow", "%"))
        self.count_checkBox.setText(_translate("MainWindow", "Ladder Range"))
        self.count_plusminus_label.setText(_translate("MainWindow", "+/-"))
        self.count_percent_label.setText(_translate("MainWindow", "%"))
        self.plot_checkBox.setText(_translate("MainWindow", "Plot"))
        self.normalMode_toolBox.setItemText(
            self.normalMode_toolBox.indexOf(self.normal_calc_page),
            _translate("MainWindow", "Calculations"),
        )
        self.plot_SAVAR_button.setText(
            _translate("MainWindow", "Generate Surface Area / Volume Plots")
        )
        self.plot_SA_button.setText(
            _translate("MainWindow", "Generate Surface Area Plots")
        )
        self.ar_csv_label.setText(_translate("MainWindow", "Aspect Ratio .CSV "))
        self.ar_browse_button.setText(_translate("MainWindow", "Browse"))
        self.savar_csv_label.setText(
            _translate("MainWindow", "Surface Area / Volume .CSV ")
        )
        self.SAVAR_browse_button.setText(_translate("MainWindow", "Browse"))
        self.GrowthRate_browse_button.setText(_translate("MainWindow", "Browse"))
        self.growthrate_cs_label.setText(_translate("MainWindow", "Growth Rates .CSV"))
        self.plot_AR_button.setText(
            _translate("MainWindow", "Generate Aspect Ratio Plots")
        )
        self.plot_vol_button.setText(_translate("MainWindow", "Generate Volume Plots"))
        self.plot_GrowthRate_button.setText(
            _translate("MainWindow", "Generate Growth Rate Plots")
        )
        self.normalMode_toolBox.setItemText(
            self.normalMode_toolBox.indexOf(self.normal_plotting_page),
            _translate("MainWindow", "Plotting Options"),
        )
        self.run_calc_button.setText(_translate("MainWindow", "RUN"))
        self.reset_button.setText(_translate("MainWindow", "RESET"))
        self.output_label.setText(_translate("MainWindow", "Output:"))
        self.output_textBox.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Arial','Arial','Arial'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
                "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'Arial'; font-weight:400;\"><br /></p></body></html>",
            )
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_normal), _translate("MainWindow", "Aspects")
        )
        self.summary_file_label.setText(
            _translate("MainWindow", "Option 1: Read Summary File")
        )
        self.select_summary_map_button.setText(
            _translate("MainWindow", "Select Summary File")
        )
        self.aspects_ouput_label.setText(
            _translate("MainWindow", "Option 2: Read Data Processor Output")
        )
        self.select_output_button1.setText(
            _translate("MainWindow", "Select Output File")
        )
        self.manual_entry_label.setText(
            _translate("MainWindow", "Option 3: Enter Manually")
        )
        self.manual_entry_button.setText(_translate("MainWindow", "Open Manual Entry"))
        self.generate_map_button.setText(_translate("MainWindow", "Generate Map"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_maps),
            _translate("MainWindow", "Crystal Maps"),
        )
        self.select_summary_slider_button.setText(
            _translate("MainWindow", "Select Summary File")
        )
        self.EVariable_title_label_2.setText(_translate("MainWindow", "Variables"))
        self.ThreeD_toolBox.setItemText(
            self.ThreeD_toolBox.indexOf(self.variables_page),
            _translate("MainWindow", "Variables"),
        )
        self.point_type_label.setText(_translate("MainWindow", "Point Type"))
        self.display_options_label.setText(_translate("MainWindow", "Display Options"))
        self.zoom_label.setText(_translate("MainWindow", "Zoom"))
        self.pointsize_label.setText(_translate("MainWindow", "Point Size"))
        self.brightness_label.setText(_translate("MainWindow", "Brightness"))
        self.resolution_label.setText(_translate("MainWindow", "Resolution"))
        self.colour_mode_label.setText(_translate("MainWindow", "Colour Mode"))
        self.colour_label.setText(_translate("MainWindow", "Colour"))
        self.colour_label_2.setText(_translate("MainWindow", "Background Colour"))
        self.ThreeD_toolBox.setItemText(
            self.ThreeD_toolBox.indexOf(self.vis_options_page),
            _translate("MainWindow", "Visualiser Options"),
        )
        self.start_3dcalc_button.setText(_translate("MainWindow", "Calculate 3D Data"))
        self.stop_3dcalc_button.setText(_translate("MainWindow", "Stop Calculation"))
        self.ThreeD_toolBox.setItemText(
            self.ThreeD_toolBox.indexOf(self.convexhull_page),
            _translate("MainWindow", "Convex Hull"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_3d), _translate("MainWindow", "3D Data")
        )
        self.simFolder_Button.setText(
            _translate("MainWindow", "Open Simulations Folder")
        )
        self.outFolder_Button.setText(_translate("MainWindow", "Go to Output Folder"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
