name: Build package

on: [push, pull_request]

jobs:
  build:
    # Check if the created reference is a tag
    if: github.event.ref_type == 'tag'

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [macos-latest]
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install hatch
      run: |
        python -m pip install --upgrade hatch

    - name: Build the project
      run: |
        hatch run pip install pyinstaller
        hatch run ./scripts/macos_bundle.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist/*.app

    create-release:
      runs-on: ubuntu-latest
      needs: build_wheels
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist 
          name: dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          files: | 
            dist/*

